# Generated by Django 6.1 on 2026-08-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '001_create_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('COMMERCE', 'Commerce'), ('CONTENT', 'Content')], max_length=30)),
                ('base_url', models.TextField(blank=True, null=True)),
                ('collection_method', models.CharField(blank=True, choices=[('API', 'API'), ('JSON', 'JSON'), ('HTML', 'HTML'), ('BROWSER', 'Browser')], max_length=30, null=True)),
                ('crawl_interval_minutes', models.IntegerField(blank=True, null=True)),
                ('requests_per_minute', models.IntegerField(blank=True, null=True)),
                ('policy_version', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"collection"."source"',
            },
        ),
    ]
