# Generated by Django 6.1 on 2026-08-31 07:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(max_length=50)),
                ('target', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.BigIntegerField(default=0)),
                ('failure_count', models.BigIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crawl_runs', to='core.source')),
            ],
            options={
                'db_table': '"collection"."crawl_run"',
            },
        ),
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('s3_bucket', models.CharField(max_length=255)),
                ('s3_key', models.TextField()),
                ('content_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crawl_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_documents', to='core.crawlrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_documents', to='core.source')),
            ],
            options={
                'db_table': '"collection"."raw_document"',
            },
        ),
        migrations.AddIndex(
            model_name='crawlrun',
            index=models.Index(fields=['source', '-started_at'], name='idx_crawl_run_source_started'),
        ),
        migrations.AddIndex(
            model_name='crawlrun',
            index=models.Index(fields=['status', '-started_at'], name='idx_crawl_run_status_started'),
        ),
        migrations.AddConstraint(
            model_name='crawlrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['RUNNING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', 'CANCELLED'])), name='ck_crawl_run_status'),
        ),
        migrations.AddConstraint(
            model_name='crawlrun',
            constraint=models.CheckConstraint(condition=models.Q(('success_count__gte', 0), ('failure_count__gte', 0)), name='ck_crawl_run_counts'),
        ),
        migrations.AddConstraint(
            model_name='crawlrun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='ck_crawl_run_time'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['source', 'external_id', 'document_type'], name='idx_raw_external'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['crawl_run'], name='idx_raw_run'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['content_hash'], name='idx_raw_hash'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['source', '-collected_at'], name='idx_raw_src_collected'),
        ),
        migrations.AddConstraint(
            model_name='rawdocument',
            constraint=models.UniqueConstraint(fields=('s3_bucket', 's3_key'), name='uq_raw_document_s3_object'),
        ),
        migrations.AddConstraint(
            model_name='rawdocument',
            constraint=models.CheckConstraint(condition=models.Q(('http_status__isnull', True), models.Q(('http_status__gte', 100), ('http_status__lte', 599)), _connector='OR'), name='ck_raw_document_http_status'),
        ),
    ]
