# Generated by Django 6.1 on 2026-08-31 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crawlrun_rawdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_type', models.CharField(choices=[('STYLE', '스타일'), ('ITEM', '아이템'), ('DETAIL', '디테일'), ('MATERIAL', '소재'), ('COLOR', '색상'), ('TPO', 'TPO')], max_length=30, verbose_name='용어 유형')),
                ('canonical_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성'), ('MERGED', '병합됨')], default='ACTIVE', max_length=20)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"dictionary"."dictionary_term"',
            },
        ),
        migrations.CreateModel(
            name='TermAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, verbose_name='별칭')),
                ('normalized_alias', models.CharField(max_length=255, verbose_name='정규화 별칭')),
                ('alias_type', models.CharField(choices=[('SYNONYM', '동의어/유사어'), ('PLATFORM', '플랫폼 표기'), ('OTHER', '기타')], default='SYNONYM', max_length=30, verbose_name='유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '용어 별칭',
                'verbose_name_plural': '용어 별칭',
                'db_table': '"dictionary"."term_alias"',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='카테고리 코드')),
                ('name', models.CharField(max_length=150, verbose_name='카테고리명')),
                ('level', models.IntegerField(default=1, verbose_name='계층레벨')),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성')], default='ACTIVE', max_length=20, verbose_name='상태')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': '"dictionary"."category"',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='color', serialize=False, to='core.dictionaryterm', verbose_name='용어')),
                ('color_family', models.CharField(blank=True, max_length=100, null=True, verbose_name='색상 계열')),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='HEX 코드')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '색상',
                'verbose_name_plural': '색상',
                'db_table': '"dictionary"."color"',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='core.dictionaryterm', verbose_name='용어')),
                ('attribute_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='속성 유형')),
                ('target_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='적용 대상')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '디테일',
                'verbose_name_plural': '디테일',
                'db_table': '"dictionary"."detail"',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='item', serialize=False, to='core.dictionaryterm', verbose_name='용어')),
                ('gender_scope', models.CharField(blank=True, max_length=30, null=True, verbose_name='성별 범위')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '아이템',
                'verbose_name_plural': '아이템',
                'db_table': '"dictionary"."item"',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='material', serialize=False, to='core.dictionaryterm', verbose_name='용어')),
                ('material_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='소재 유형')),
                ('process_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='가공 방식')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '소재',
                'verbose_name_plural': '소재',
                'db_table': '"dictionary"."material"',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='style', serialize=False, to='core.dictionaryterm', verbose_name='용어')),
                ('style_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='스타일 그룹')),
                ('is_core', models.BooleanField(default=False, verbose_name='핵심 스타일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '스타일',
                'verbose_name_plural': '스타일',
                'db_table': '"dictionary"."style"',
            },
        ),
        migrations.CreateModel(
            name='TPO',
            fields=[
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tpo', serialize=False, to='core.dictionaryterm', verbose_name='용어')),
                ('tpo_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='TPO 유형')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TPO',
                'verbose_name_plural': 'TPO',
                'db_table': '"dictionary"."tpo"',
            },
        ),
        migrations.AddConstraint(
            model_name='dictionaryterm',
            constraint=models.UniqueConstraint(fields=('term_type', 'normalized_name'), name='uq_dict_term_name'),
        ),
        migrations.AddConstraint(
            model_name='dictionaryterm',
            constraint=models.CheckConstraint(condition=models.Q(('term_type__in', ['STYLE', 'ITEM', 'DETAIL', 'MATERIAL', 'COLOR', 'TPO'])), name='ck_dict_term_type'),
        ),
        migrations.AddConstraint(
            model_name='dictionaryterm',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE', 'MERGED'])), name='ck_dict_term_status'),
        ),
        migrations.AddConstraint(
            model_name='dictionaryterm',
            constraint=models.CheckConstraint(condition=models.Q(('last_seen_at__isnull', True), ('first_seen_at__isnull', True), ('last_seen_at__gte', models.F('first_seen_at')), _connector='OR'), name='ck_dict_term_seen'),
        ),
        migrations.AddField(
            model_name='termalias',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_aliases', to='core.source', verbose_name='출처'),
        ),
        migrations.AddField(
            model_name='termalias',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.dictionaryterm', verbose_name='표준 용어'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='ck_category_level'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__isnull', True), ('sort_order__gte', 0), _connector='OR'), name='ck_category_sort'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE'])), name='ck_category_status'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('parent', models.F('id')), _negated=True), _connector='OR'), name='ck_category_self'),
        ),
        migrations.AddField(
            model_name='color',
            name='base_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_colors', to='core.color', verbose_name='기본 색상'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.category', verbose_name='카테고리'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.CheckConstraint(condition=models.Q(('base_color__isnull', True), models.Q(('base_color', models.F('term')), _negated=True), _connector='OR'), name='ck_color_self'),
        ),
    ]
