# Generated by Django 6.1 on 2026-08-31 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dictionaryterm_termalias_category_color_detail_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=255, verbose_name='표준 브랜드명')),
                ('normalized_name', models.CharField(max_length=255, unique=True, verbose_name='정규화 브랜드명')),
                ('english_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='영문명')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='국가 코드')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성')], default='ACTIVE', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': '브랜드',
                'db_table': '"dictionary"."brand"',
            },
        ),
        migrations.CreateModel(
            name='TermCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_term', models.CharField(max_length=255, verbose_name='원본 용어')),
                ('normalized_term', models.CharField(max_length=255, verbose_name='정규화 용어')),
                ('suggested_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='추천 유형')),
                ('detected_count', models.BigIntegerField(default=1, verbose_name='발견 횟수')),
                ('confidence', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='신뢰도')),
                ('detected_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='발견 출처')),
                ('example_context', models.TextField(blank=True, null=True, verbose_name='예시 문맥')),
                ('status', models.CharField(choices=[('PENDING', '검토 대기'), ('APPROVED', '승인'), ('REJECTED', '제외')], default='PENDING', max_length=20, verbose_name='상태')),
                ('first_seen_at', models.DateTimeField(verbose_name='최초 발견일시')),
                ('last_seen_at', models.DateTimeField(verbose_name='최근 발견일시')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '용어 후보',
                'verbose_name_plural': '용어 후보',
                'db_table': '"dictionary"."term_candidate"',
                'indexes': [models.Index(fields=['normalized_term', 'suggested_type'], name='idx_term_cand_norm'), models.Index(fields=['status', '-detected_count'], name='idx_term_cand_status')],
            },
        ),
        migrations.CreateModel(
            name='BrandAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, verbose_name='별칭')),
                ('normalized_alias', models.CharField(max_length=255, verbose_name='정규화 별칭')),
                ('language', models.CharField(default='ko', max_length=10, verbose_name='언어')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.brand', verbose_name='브랜드')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_aliases', to='core.source', verbose_name='출처')),
            ],
            options={
                'verbose_name': '브랜드 별칭',
                'verbose_name_plural': '브랜드 별칭',
                'db_table': '"dictionary"."brand_alias"',
                'indexes': [models.Index(fields=['source', 'normalized_alias'], name='idx_brand_alias_src')],
                'constraints': [models.UniqueConstraint(fields=('brand', 'normalized_alias', 'language'), name='uq_brand_alias')],
            },
        ),
        migrations.CreateModel(
            name='CategoryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_category_id', models.CharField(max_length=255, verbose_name='원본 카테고리 ID')),
                ('source_category_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='원본 카테고리명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.category', verbose_name='표준 카테고리')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_aliases', to='core.source', verbose_name='출처')),
            ],
            options={
                'verbose_name': '카테고리 매핑',
                'verbose_name_plural': '카테고리 매핑',
                'db_table': '"dictionary"."category_alias"',
                'constraints': [models.UniqueConstraint(fields=('source', 'source_category_id'), name='uq_cat_alias_src')],
            },
        ),
        migrations.CreateModel(
            name='TermRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=50, verbose_name='관계 유형')),
                ('weight', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='가중치')),
                ('confidence', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='신뢰도')),
                ('relation_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='관계 출처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='core.dictionaryterm', verbose_name='기준 용어')),
                ('target_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='core.dictionaryterm', verbose_name='연관 용어')),
            ],
            options={
                'verbose_name': '용어 관계',
                'verbose_name_plural': '용어 관계',
                'db_table': '"dictionary"."term_relation"',
                'indexes': [models.Index(fields=['source_term', 'relation_type'], name='idx_term_rel_src'), models.Index(fields=['target_term', 'relation_type'], name='idx_term_rel_tgt')],
                'constraints': [models.UniqueConstraint(fields=('source_term', 'target_term', 'relation_type'), name='uq_term_relation'), models.CheckConstraint(condition=models.Q(('source_term', models.F('target_term')), _negated=True), name='ck_term_rel_self')],
            },
        ),
    ]
