# Generated by Django 6.1 on 2026-08-31 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brand_termcandidate_brandalias_categoryalias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=500, verbose_name='상품명')),
                ('normalized_name', models.CharField(max_length=500, verbose_name='검색용 상품명')),
                ('gender_scope', models.CharField(blank=True, max_length=30, null=True, verbose_name='성별 범위')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='상품 속성')),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성')], default='ACTIVE', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.brand', verbose_name='브랜드')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category', verbose_name='카테고리')),
                ('item_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.item', verbose_name='아이템')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': '"commerce"."product"',
            },
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_product_id', models.CharField(max_length=255, verbose_name='플랫폼 상품 ID')),
                ('market_type', models.CharField(choices=[('RETAIL', '일반 판매'), ('RESALE', '리셀')], default='RETAIL', max_length=20, verbose_name='판매 유형')),
                ('product_url', models.TextField(blank=True, null=True, verbose_name='상품 URL')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 발견일시')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 확인일시')),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성')], default='ACTIVE', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.product', verbose_name='표준 상품')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sources', to='core.source', verbose_name='플랫폼')),
            ],
            options={
                'verbose_name': '플랫폼 상품',
                'verbose_name_plural': '플랫폼 상품',
                'db_table': '"commerce"."product_source"',
            },
        ),
        migrations.CreateModel(
            name='ProductSourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='관측일시')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='정가')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='판매가')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='할인율')),
                ('rank_position', models.IntegerField(blank=True, null=True, verbose_name='순위')),
                ('ranking_scope', models.CharField(blank=True, max_length=50, null=True, verbose_name='랭킹 범위')),
                ('ranking_context', models.JSONField(blank=True, default=dict, verbose_name='랭킹 조건')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='평점')),
                ('review_count', models.BigIntegerField(blank=True, null=True, verbose_name='리뷰 수')),
                ('like_count', models.BigIntegerField(blank=True, null=True, verbose_name='좋아요 수')),
                ('stock_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='재고 상태')),
                ('platform_metrics', models.JSONField(blank=True, default=dict, verbose_name='플랫폼 추가 지표')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('product_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.productsource', verbose_name='플랫폼 상품')),
            ],
            options={
                'verbose_name': '상품 스냅샷',
                'verbose_name_plural': '상품 스냅샷',
                'db_table': '"snapshot"."product_source_snapshot"',
            },
        ),
        migrations.CreateModel(
            name='ResaleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='관측일시')),
                ('listing_count', models.IntegerField(blank=True, null=True, verbose_name='등록 수')),
                ('available_count', models.IntegerField(blank=True, null=True, verbose_name='판매 가능 수')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='최저가')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='최고가')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='평균가')),
                ('median_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='중앙값')),
                ('sold_count', models.BigIntegerField(blank=True, null=True, verbose_name='판매 수')),
                ('lowest_ask', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='최저 판매가')),
                ('highest_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='최고 구매가')),
                ('last_trade_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='최근 거래가')),
                ('trade_volume', models.BigIntegerField(blank=True, null=True, verbose_name='거래량')),
                ('resale_price_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='리셀 가격 비율')),
                ('resale_index', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='리셀 지수')),
                ('market_metrics', models.JSONField(blank=True, default=dict, verbose_name='추가 시장 지표')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('product_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resale_snapshots', to='core.productsource', verbose_name='리셀 상품')),
            ],
            options={
                'verbose_name': '리셀 스냅샷',
                'verbose_name_plural': '리셀 스냅샷',
                'db_table': '"snapshot"."resale_snapshot"',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'normalized_name'], name='idx_product_brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_product_cat'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['item_term'], name='idx_product_item'),
        ),
        migrations.AddIndex(
            model_name='productsource',
            index=models.Index(fields=['product'], name='idx_prod_src_prod'),
        ),
        migrations.AddIndex(
            model_name='productsource',
            index=models.Index(fields=['market_type'], name='idx_prod_src_market'),
        ),
        migrations.AddConstraint(
            model_name='productsource',
            constraint=models.UniqueConstraint(fields=('source', 'source_product_id'), name='uq_product_src'),
        ),
        migrations.AddIndex(
            model_name='productsourcesnapshot',
            index=models.Index(fields=['-observed_at'], name='idx_prod_snap_time'),
        ),
        migrations.AddIndex(
            model_name='productsourcesnapshot',
            index=models.Index(fields=['product_source', 'rank_position'], name='idx_prod_snap_rank'),
        ),
        migrations.AddConstraint(
            model_name='productsourcesnapshot',
            constraint=models.UniqueConstraint(fields=('product_source', 'observed_at'), name='uq_prod_snapshot'),
        ),
        migrations.AddIndex(
            model_name='resalesnapshot',
            index=models.Index(fields=['-observed_at', '-resale_index'], name='idx_resale_index'),
        ),
        migrations.AddIndex(
            model_name='resalesnapshot',
            index=models.Index(fields=['product_source'], name='idx_resale_prod'),
        ),
        migrations.AddConstraint(
            model_name='resalesnapshot',
            constraint=models.UniqueConstraint(fields=('product_source', 'observed_at'), name='uq_resale_snap'),
        ),
    ]
