# Generated by Django 6.1 on 2026-08-31 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_productsource_productsourcesnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_profile_id', models.CharField(max_length=255, verbose_name='플랫폼 프로필 ID')),
                ('profile_type', models.CharField(max_length=30, verbose_name='프로필 유형')),
                ('name', models.CharField(max_length=300, verbose_name='프로필명')),
                ('handle', models.CharField(blank=True, max_length=200, null=True, verbose_name='핸들')),
                ('profile_url', models.TextField(blank=True, null=True, verbose_name='프로필 URL')),
                ('profile_image_url', models.TextField(blank=True, null=True, verbose_name='프로필 이미지')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('platform_metadata', models.JSONField(blank=True, default=dict, verbose_name='플랫폼 추가 정보')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 발견일시')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 확인일시')),
                ('status', models.CharField(default='ACTIVE', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_profiles', to='core.source', verbose_name='플랫폼')),
            ],
            options={
                'verbose_name': '콘텐츠 프로필',
                'verbose_name_plural': '콘텐츠 프로필',
                'db_table': '"content"."content_profile"',
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_content_id', models.CharField(max_length=255, verbose_name='플랫폼 콘텐츠 ID')),
                ('content_type', models.CharField(choices=[('VIDEO', '영상'), ('SHORTS', '쇼츠'), ('POST', '게시글'), ('ARTICLE', '기사')], max_length=30, verbose_name='콘텐츠 유형')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('content_url', models.TextField(verbose_name='콘텐츠 URL')),
                ('thumbnail_url', models.TextField(blank=True, null=True, verbose_name='썸네일')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='게시일시')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='재생시간(초)')),
                ('analysis_tags', models.JSONField(blank=True, default=list, verbose_name='분석 태그')),
                ('analysis_status', models.CharField(default='PENDING', max_length=20, verbose_name='분석 상태')),
                ('platform_metadata', models.JSONField(blank=True, default=dict, verbose_name='플랫폼 추가 정보')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 발견일시')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 확인일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to='core.source', verbose_name='플랫폼')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='core.contentprofile', verbose_name='프로필')),
            ],
            options={
                'verbose_name': '콘텐츠',
                'verbose_name_plural': '콘텐츠',
                'db_table': '"content"."content_item"',
            },
        ),
        migrations.CreateModel(
            name='ContentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='관측일시')),
                ('view_count', models.BigIntegerField(blank=True, null=True, verbose_name='조회수')),
                ('like_count', models.BigIntegerField(blank=True, null=True, verbose_name='좋아요 수')),
                ('comment_count', models.BigIntegerField(blank=True, null=True, verbose_name='댓글 수')),
                ('share_count', models.BigIntegerField(blank=True, null=True, verbose_name='공유 수')),
                ('save_count', models.BigIntegerField(blank=True, null=True, verbose_name='저장 수')),
                ('engagement_count', models.BigIntegerField(blank=True, null=True, verbose_name='반응 수')),
                ('platform_metrics', models.JSONField(blank=True, default=dict, verbose_name='플랫폼 추가 지표')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.contentitem', verbose_name='콘텐츠')),
            ],
            options={
                'verbose_name': '콘텐츠 스냅샷',
                'verbose_name_plural': '콘텐츠 스냅샷',
                'db_table': '"snapshot"."content_snapshot"',
            },
        ),
        migrations.AddIndex(
            model_name='contentprofile',
            index=models.Index(fields=['source', 'name'], name='idx_content_prof_src'),
        ),
        migrations.AddIndex(
            model_name='contentprofile',
            index=models.Index(fields=['profile_type'], name='idx_content_prof_type'),
        ),
        migrations.AddConstraint(
            model_name='contentprofile',
            constraint=models.UniqueConstraint(fields=('source', 'external_profile_id'), name='uq_content_profile'),
        ),
        migrations.AddConstraint(
            model_name='contentitem',
            constraint=models.UniqueConstraint(fields=('source', 'external_content_id'), name='uq_content_item'),
        ),
        migrations.AddIndex(
            model_name='contentsnapshot',
            index=models.Index(fields=['-observed_at'], name='idx_content_snap_time'),
        ),
        migrations.AddIndex(
            model_name='contentsnapshot',
            index=models.Index(fields=['content_item'], name='idx_content_snap_item'),
        ),
        migrations.AddConstraint(
            model_name='contentsnapshot',
            constraint=models.UniqueConstraint(fields=('content_item', 'observed_at'), name='uq_content_snapshot'),
        ),
    ]
