# Generated by Django 6.1 on 2026-08-31 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contentprofile_contentitem_contentsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermAssocDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(verbose_name='기준일')),
                ('cooccurrence_count', models.BigIntegerField(default=0, verbose_name='동시 언급 수')),
                ('association_score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='연관도')),
                ('confidence', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='신뢰도')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='추가 지표')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assoc_sources', to='core.dictionaryterm', verbose_name='기준 용어')),
                ('target_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assoc_targets', to='core.dictionaryterm', verbose_name='연관 용어')),
            ],
            options={
                'verbose_name': '용어 일별 연관',
                'verbose_name_plural': '용어 일별 연관',
                'db_table': '"analysis"."term_assoc_daily"',
                'indexes': [models.Index(fields=['source_term', '-metric_date'], name='idx_assoc_src_day'), models.Index(fields=['metric_date', '-association_score'], name='idx_assoc_score')],
                'constraints': [models.UniqueConstraint(fields=('source_term', 'target_term', 'metric_date'), name='uq_term_assoc_day'), models.CheckConstraint(condition=models.Q(('source_term', models.F('target_term')), _negated=True), name='ck_term_assoc_self')],
            },
        ),
        migrations.CreateModel(
            name='TermMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(verbose_name='기준일')),
                ('mention_count', models.BigIntegerField(default=0, verbose_name='언급 수')),
                ('document_count', models.BigIntegerField(default=0, verbose_name='문서 수')),
                ('source_count', models.IntegerField(default=0, verbose_name='플랫폼 수')),
                ('sentiment_avg', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='평균 감성')),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='증가율')),
                ('trend_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='트렌드 점수')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='추가 지표')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='core.dictionaryterm', verbose_name='용어')),
            ],
            options={
                'verbose_name': '용어 일별 지표',
                'verbose_name_plural': '용어 일별 지표',
                'db_table': '"analysis"."term_metric_daily"',
                'indexes': [models.Index(fields=['metric_date', '-trend_score'], name='idx_term_metric_trend'), models.Index(fields=['term', '-metric_date'], name='idx_term_metric_term')],
                'constraints': [models.UniqueConstraint(fields=('term', 'metric_date'), name='uq_term_metric_day')],
            },
        ),
        migrations.CreateModel(
            name='TextDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TRANSCRIPT', '자막'), ('COMMENT', '댓글'), ('REVIEW', '리뷰'), ('DESCRIPTION', '설명'), ('ARTICLE', '본문')], max_length=30, verbose_name='문서 유형')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='플랫폼 문서 ID')),
                ('body', models.TextField(verbose_name='분석 텍스트')),
                ('language', models.CharField(default='ko', max_length=10, verbose_name='언어')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='감성 점수')),
                ('intent_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='의도 코드')),
                ('extracted_terms', models.JSONField(blank=True, default=list, verbose_name='추출 용어')),
                ('analysis_metadata', models.JSONField(blank=True, default=dict, verbose_name='분석 추가 정보')),
                ('analysis_status', models.CharField(choices=[('PENDING', '대기'), ('PROCESSING', '분석 중'), ('DONE', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20, verbose_name='분석 상태')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='분석일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_documents', to='core.contentitem', verbose_name='콘텐츠')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text_documents', to='core.source', verbose_name='플랫폼')),
            ],
            options={
                'verbose_name': '분석 문서',
                'verbose_name_plural': '분석 문서',
                'db_table': '"analysis"."text_document"',
                'indexes': [models.Index(fields=['content_item', 'document_type'], name='idx_text_doc_content'), models.Index(fields=['analysis_status'], name='idx_text_doc_status'), models.Index(fields=['-created_at'], name='idx_text_doc_created')],
            },
        ),
    ]
