# Generated by Django 6.1 on 2026-08-31 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_termassocdaily_termmetricdaily_textdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='닉네임')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='성별')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='출생연도')),
                ('body_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='체형')),
                ('profile_metadata', models.JSONField(blank=True, default=dict, verbose_name='추가 프로필 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedit_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': '"app"."app_user"',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='대화 제목')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='세션 컨텍스트')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 대화일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='core.appuser', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '챗봇 세션',
                'verbose_name_plural': '챗봇 세션',
                'db_table': '"app"."chat_session"',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', '사용자'), ('ASSISTANT', 'AI'), ('SYSTEM', '시스템')], max_length=20, verbose_name='메시지 역할')),
                ('content', models.TextField(verbose_name='내용')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='추가 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession', verbose_name='대화')),
            ],
            options={
                'verbose_name': '챗봇 메시지',
                'verbose_name_plural': '챗봇 메시지',
                'db_table': '"app"."chat_message"',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VIEW', '조회'), ('CLICK', '클릭'), ('SAVE', '저장'), ('SEARCH', '검색'), ('VOTE', '투표'), ('CHAT', '챗봇')], max_length=30, verbose_name='행동 유형')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='행동 추가 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생일시')),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events', to='core.contentitem', verbose_name='콘텐츠')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events', to='core.product', verbose_name='상품')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events', to='core.dictionaryterm', verbose_name='용어')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.appuser', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 행동',
                'verbose_name_plural': '사용자 행동',
                'db_table': '"app"."user_event"',
            },
        ),
        migrations.CreateModel(
            name='UserSavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core.contentitem', verbose_name='콘텐츠')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='core.appuser', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '저장 항목',
                'verbose_name_plural': '저장 항목',
                'db_table': '"app"."user_saved_item"',
            },
        ),
        migrations.CreateModel(
            name='UserTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_type', models.CharField(choices=[('TERM', '용어'), ('BRAND', '브랜드'), ('CATEGORY', '카테고리')], max_length=20, verbose_name='취향 유형')),
                ('weight', models.DecimalField(decimal_places=5, default=1, max_digits=6, verbose_name='관심 가중치')),
                ('source', models.CharField(default='USER', max_length=30, verbose_name='취향 출처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tastes', to='core.brand', verbose_name='브랜드')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tastes', to='core.category', verbose_name='카테고리')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tastes', to='core.dictionaryterm', verbose_name='용어')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tastes', to='core.appuser', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 취향',
                'verbose_name_plural': '사용자 취향',
                'db_table': '"app"."user_taste"',
            },
        ),
        migrations.CreateModel(
            name='VoteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('image_url', models.TextField(blank=True, null=True, verbose_name='이미지 URL')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='태그')),
                ('status', models.CharField(choices=[('ACTIVE', '진행 중'), ('CLOSED', '종료')], default='ACTIVE', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_cards', to='core.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_cards', to='core.appuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '살말 카드',
                'verbose_name_plural': '살말 카드',
                'db_table': '"app"."vote_card"',
            },
        ),
        migrations.CreateModel(
            name='VoteBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('BUY', '살'), ('PASS', '말')], max_length=10, verbose_name='선택')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='투표일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_ballots', to='core.appuser', verbose_name='사용자')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='core.votecard', verbose_name='살말 카드')),
            ],
            options={
                'verbose_name': '살말 투표',
                'verbose_name_plural': '살말 투표',
                'db_table': '"app"."vote_ballot"',
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='idx_chat_session_user'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='idx_chat_msg_session'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user', '-created_at'], name='idx_event_user_time'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', '-created_at'], name='idx_event_type_time'),
        ),
        migrations.AddIndex(
            model_name='usersaveditem',
            index=models.Index(fields=['user', '-created_at'], name='idx_saved_user_time'),
        ),
        migrations.AddIndex(
            model_name='usertaste',
            index=models.Index(fields=['user', 'taste_type'], name='idx_taste_user_type'),
        ),
        migrations.AddIndex(
            model_name='votecard',
            index=models.Index(fields=['status', '-created_at'], name='idx_vote_card_status'),
        ),
        migrations.AddConstraint(
            model_name='voteballot',
            constraint=models.UniqueConstraint(fields=('card', 'user'), name='uq_vote_ballot'),
        ),
    ]
