# Generated by Django 6.1 on 2026-09-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appuser_chatsession_chatmessage_userevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level', 'sort_order', 'code'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='카테고리 코드'),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='계층 레벨'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='정렬 순서'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성')], db_index=True, default='ACTIVE', max_length=20, verbose_name='상태'),
        ),
    ]
