# Generated by Django 6.1 on 2026-09-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_options_alter_category_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryterm',
            options={'ordering': ['term_type', 'term_code'], 'verbose_name': '사전 용어', 'verbose_name_plural': '사전 용어'},
        ),
        migrations.AddField(
            model_name='dictionaryterm',
            name='term_code',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, verbose_name='용어 코드'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='canonical_name',
            field=models.CharField(max_length=255, verbose_name='표준 용어명'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='영문명'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최초 관측일'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최근 관측일'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='normalized_name',
            field=models.CharField(max_length=255, verbose_name='정규화 용어명'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성'), ('MERGED', '병합됨')], db_index=True, default='ACTIVE', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
