# Generated by Django 6.1 on 2026-09-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_dictionaryterm_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'level', 'sort_order', 'code'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('PRODUCT', '상품 카테고리'), ('BRAND', '브랜드 카테고리')], db_index=True, default='PRODUCT', max_length=20, verbose_name='카테고리 유형'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=100, verbose_name='카테고리 코드'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('category_type', 'code'), name='uq_category_type_code'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('category_type__in', ['PRODUCT', 'BRAND'])), name='ck_category_type'),
        ),
    ]
