# Generated by Django 6.1 on 2026-09-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_category_options_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'level', 'sort_order', 'code']},
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='uq_category_type_code',
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='카테고리 코드'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
