# Generated by Django 6.1 on 2026-09-01 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='canonical_name',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='normalized_name',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_code',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'BRAND'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='core.category', verbose_name='브랜드 카테고리'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성')], db_index=True, default='ACTIVE', max_length=20, verbose_name='상태'),
        ),
    ]
