# Generated by Django 6.1 on 2026-09-01 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_brand_options_remove_brand_canonical_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color_family', 'term__canonical_name'], 'verbose_name': '색상', 'verbose_name_plural': '색상'},
        ),
        migrations.RemoveConstraint(
            model_name='color',
            name='ck_color_self',
        ),
        migrations.AlterField(
            model_name='color',
            name='base_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_colors', to='core.color', verbose_name='기준 색상'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_family',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='색상 계열'),
        ),
        migrations.AlterField(
            model_name='color',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='color',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='color',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.CheckConstraint(condition=models.Q(('base_color__isnull', True), models.Q(('base_color', models.F('term')), _negated=True), _connector='OR'), name='ck_color_self_base'),
        ),
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
    ]
