# Generated by Django 6.1 on 2026-09-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_color_options_remove_color_ck_color_self_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpo',
            options={'ordering': ['tpo_type', 'term__canonical_name'], 'verbose_name': 'TPO', 'verbose_name_plural': 'TPO'},
        ),
        migrations.AlterField(
            model_name='tpo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='tpo',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='tpo',
            name='tpo_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='TPO 유형'),
        ),
        migrations.AlterField(
            model_name='tpo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
