# Generated by Django 6.1 on 2026-09-01 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_tpo_options_alter_tpo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='attribute_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='속성 유형'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'PRODUCT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.category', verbose_name='카테고리'),
        ),
    ]
