# Generated by Django 6.1 on 2026-09-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_detail_attribute_type_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='소재 유형'),
        ),
        migrations.AlterField(
            model_name='material',
            name='process_type',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='조직/가공 유형'),
        ),
    ]
