# Generated by Django 6.1 on 2026-09-01 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_material_material_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_terms', to='core.product', verbose_name='상품')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_terms', to='core.dictionaryterm', verbose_name='상품 특성')),
            ],
            options={
                'verbose_name': '상품 특성',
                'verbose_name_plural': '상품 특성',
                'db_table': '"commerce"."product_term"',
                'constraints': [models.UniqueConstraint(fields=('product', 'term'), name='uq_product_term')],
            },
        ),
    ]
