# Generated by Django 6.1 on 2026-09-02 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_productterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('PRODUCT', 'Product'), ('RANKING', 'Ranking'), ('STORE', 'Store'), ('REVIEW', 'Review'), ('CREATOR', 'Creator'), ('VIDEO', 'Video')], max_length=30)),
                ('target_url', models.TextField(blank=True, null=True)),
                ('collection_mode', models.CharField(choices=[('LIVE', 'Live'), ('BACKFILL', 'Backfill')], default='LIVE', max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('next_crawl_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"collection"."crawl_target"',
            },
        ),
        migrations.RemoveConstraint(
            model_name='crawlrun',
            name='ck_crawl_run_status',
        ),
        migrations.RemoveConstraint(
            model_name='crawlrun',
            name='ck_crawl_run_counts',
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='discovered_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='run_type',
            field=models.CharField(choices=[('LIVE', 'Live'), ('BACKFILL', 'Backfill'), ('MANUAL', 'Manual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='crawltarget',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crawl_targets', to='core.source'),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='crawl_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_runs', to='core.crawltarget'),
        ),
        migrations.AddIndex(
            model_name='crawlrun',
            index=models.Index(fields=['crawl_target', '-started_at'], name='idx_run_target_started'),
        ),
        migrations.AddConstraint(
            model_name='crawlrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', 'CANCELLED'])), name='ck_crawl_run_status'),
        ),
        migrations.AddConstraint(
            model_name='crawlrun',
            constraint=models.CheckConstraint(condition=models.Q(('discovered_count__gte', 0), ('success_count__gte', 0), ('failure_count__gte', 0)), name='ck_crawl_run_counts'),
        ),
        migrations.AddIndex(
            model_name='crawltarget',
            index=models.Index(fields=['source', 'is_active'], name='idx_target_src_active'),
        ),
        migrations.AddIndex(
            model_name='crawltarget',
            index=models.Index(fields=['collection_mode', 'is_active'], name='idx_target_mode_active'),
        ),
        migrations.AddIndex(
            model_name='crawltarget',
            index=models.Index(fields=['next_crawl_at'], name='idx_target_next_crawl'),
        ),
    ]
