# Generated by Django 6.1 on 2026-09-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_crawltarget_remove_crawlrun_ck_crawl_run_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawltarget',
            name='name',
            field=models.CharField(blank=True, default='', help_text='사람이 알아보기 쉬운 타깃 이름. 예: 남성 상의 전체연령 DAILY', max_length=200),
        ),
    ]
