# Generated by Django 6.1 on 2026-09-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_crawltarget_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', '남성'), ('FEMALE', '여성'), ('MIXED', '혼성'), ('UNKNOWN', '미상')], default='UNKNOWN', max_length=20, verbose_name='크리에이터 성별'),
        ),
        migrations.AddIndex(
            model_name='contentprofile',
            index=models.Index(fields=['gender'], name='idx_content_prof_gender'),
        ),
    ]
