# Generated by Django 6.1 on 2026-09-02 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_contentprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('BRAND', '브랜드'), ('CATEGORY', '카테고리'), ('DETAIL', '디테일'), ('MATERIAL', '소재'), ('COLOR', '색상'), ('ITEM', '아이템'), ('STYLE', '스타일'), ('TAG', '태그')], db_index=True, max_length=30, verbose_name='매핑 유형')),
                ('source_key', models.CharField(db_index=True, max_length=255, verbose_name='원본 키')),
                ('source_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='원본명')),
                ('source_detail', models.JSONField(blank=True, default=dict, verbose_name='원본 상세 정보')),
                ('suggested_target_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='추천 대상 유형')),
                ('suggested_target_id', models.BigIntegerField(blank=True, null=True, verbose_name='추천 대상 ID')),
                ('suggested_target_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='추천 대상명')),
                ('selected_target_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='선택 대상 유형')),
                ('selected_target_id', models.BigIntegerField(blank=True, null=True, verbose_name='선택 대상 ID')),
                ('selected_target_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='선택 대상명')),
                ('match_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='매칭 방식')),
                ('confidence', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='신뢰도')),
                ('detected_count', models.BigIntegerField(default=1, verbose_name='발견 횟수')),
                ('sample_entity_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='예시 엔터티 ID')),
                ('sample_entity_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='예시 엔터티명')),
                ('status', models.CharField(choices=[('PENDING', '검토 대기'), ('APPROVED', '승인'), ('CREATE', '신규 생성'), ('REJECTED', '제외')], db_index=True, default='PENDING', max_length=20, verbose_name='상태')),
                ('note', models.TextField(blank=True, null=True, verbose_name='검토 메모')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 발견일시')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 발견일시')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping_candidates', to='core.source', verbose_name='출처')),
            ],
            options={
                'verbose_name': '매핑 후보',
                'verbose_name_plural': '매핑 후보',
                'db_table': '"dictionary"."mapping_candidate"',
                'indexes': [models.Index(fields=['mapping_type', 'status'], name='idx_mapping_type_status'), models.Index(fields=['source', 'status'], name='idx_mapping_source_status')],
                'constraints': [models.UniqueConstraint(fields=('source', 'mapping_type', 'source_key'), name='uq_mapping_candidate')],
            },
        ),
    ]
