# Generated by Django 6.1 on 2026-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_mappingcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandalias',
            name='source_brand_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='플랫폼 브랜드 ID'),
        ),
        migrations.AddIndex(
            model_name='brandalias',
            index=models.Index(fields=['source', 'source_brand_id'], name='idx_brand_alias_src_id'),
        ),
        migrations.AddConstraint(
            model_name='brandalias',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False), ('source_brand_id__isnull', False)), fields=('source', 'source_brand_id'), name='uq_brand_alias_source_brand_id'),
        ),
    ]
