# Generated by Django 6.1 on 2026-09-02 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_brandalias_source_brand_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_brand_id', models.CharField(max_length=255, verbose_name='플랫폼 브랜드 ID')),
                ('source_brand_name', models.CharField(db_index=True, max_length=255, verbose_name='플랫폼 브랜드명')),
                ('source_brand_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='플랫폼 브랜드 URL')),
                ('is_official', models.BooleanField(default=False, verbose_name='공식 입점 여부')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 관측일')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 관측일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '플랫폼 브랜드 매핑',
                'verbose_name_plural': '플랫폼 브랜드 매핑',
                'db_table': '"dictionary"."brand_source"',
            },
        ),
        migrations.RemoveIndex(
            model_name='brandalias',
            name='idx_brand_alias_src',
        ),
        migrations.RemoveIndex(
            model_name='brandalias',
            name='idx_brand_alias_src_id',
        ),
        migrations.RemoveConstraint(
            model_name='brandalias',
            name='uq_brand_alias',
        ),
        migrations.RemoveConstraint(
            model_name='brandalias',
            name='uq_brand_alias_source_brand_id',
        ),
        migrations.RemoveConstraint(
            model_name='dictionaryterm',
            name='ck_dict_term_type',
        ),
        migrations.AddField(
            model_name='dictionaryterm',
            name='brand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_term', to='core.brand', verbose_name='표준 브랜드'),
        ),
        migrations.AddField(
            model_name='termalias',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='term_type',
            field=models.CharField(choices=[('BRAND', '브랜드'), ('STYLE', '스타일'), ('ITEM', '아이템'), ('DETAIL', '디테일'), ('MATERIAL', '소재'), ('COLOR', '색상'), ('TPO', 'TPO')], max_length=30, verbose_name='용어 유형'),
        ),
        migrations.AlterField(
            model_name='termalias',
            name='alias',
            field=models.CharField(db_index=True, max_length=255, verbose_name='별칭'),
        ),
        migrations.AlterField(
            model_name='termalias',
            name='alias_type',
            field=models.CharField(choices=[('SYNONYM', '동의어/유사어'), ('PLATFORM', '플랫폼 표기'), ('OTHER', '기타')], db_index=True, default='SYNONYM', max_length=30, verbose_name='유형'),
        ),
        migrations.AlterField(
            model_name='termalias',
            name='normalized_alias',
            field=models.CharField(db_index=True, max_length=255, verbose_name='정규화 별칭'),
        ),
        migrations.AddIndex(
            model_name='termalias',
            index=models.Index(fields=['normalized_alias'], name='idx_term_alias_norm'),
        ),
        migrations.AddIndex(
            model_name='termalias',
            index=models.Index(fields=['source', 'normalized_alias'], name='idx_term_alias_src_norm'),
        ),
        migrations.AddIndex(
            model_name='termalias',
            index=models.Index(fields=['term', 'normalized_alias'], name='idx_term_alias_term_norm'),
        ),
        migrations.AddConstraint(
            model_name='dictionaryterm',
            constraint=models.CheckConstraint(condition=models.Q(('term_type__in', ['BRAND', 'STYLE', 'ITEM', 'DETAIL', 'MATERIAL', 'COLOR', 'TPO'])), name='ck_dict_term_type'),
        ),
        migrations.AddConstraint(
            model_name='termalias',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', True)), fields=('term', 'normalized_alias'), name='uq_term_alias_global'),
        ),
        migrations.AddConstraint(
            model_name='termalias',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False)), fields=('term', 'normalized_alias', 'source'), name='uq_term_alias_source'),
        ),
        migrations.AddField(
            model_name='brandsource',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='core.brand', verbose_name='표준 브랜드'),
        ),
        migrations.AddField(
            model_name='brandsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_sources', to='core.source', verbose_name='출처'),
        ),
        migrations.RemoveField(
            model_name='brandalias',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='brandalias',
            name='source',
        ),
        migrations.AddIndex(
            model_name='brandsource',
            index=models.Index(fields=['brand'], name='idx_brand_source_brand'),
        ),
        migrations.AddIndex(
            model_name='brandsource',
            index=models.Index(fields=['source', 'source_brand_name'], name='idx_brand_source_src_name'),
        ),
        migrations.AddConstraint(
            model_name='brandsource',
            constraint=models.UniqueConstraint(fields=('source', 'source_brand_id'), name='uq_brand_source_src_id'),
        ),
        migrations.AddConstraint(
            model_name='brandsource',
            constraint=models.CheckConstraint(condition=models.Q(('last_seen_at__isnull', True), ('first_seen_at__isnull', True), ('last_seen_at__gte', models.F('first_seen_at')), _connector='OR'), name='ck_brand_source_seen'),
        ),
        migrations.DeleteModel(
            name='BrandAlias',
        ),
    ]
