# Generated by Django 6.1 on 2026-09-03 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_brandsource_remove_brandalias_idx_brand_alias_src_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandsource',
            options={'verbose_name': '플랫폼 브랜드', 'verbose_name_plural': '플랫폼 브랜드'},
        ),
        migrations.AlterModelOptions(
            name='dictionaryterm',
            options={},
        ),
        migrations.AlterModelOptions(
            name='termalias',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='dictionaryterm',
            name='ck_dict_term_seen',
        ),
        migrations.RemoveIndex(
            model_name='brandsource',
            name='idx_brand_source_src_name',
        ),
        migrations.RemoveIndex(
            model_name='termalias',
            name='idx_term_alias_term_norm',
        ),
        migrations.AddField(
            model_name='brandsource',
            name='detected_count',
            field=models.BigIntegerField(default=1, verbose_name='발견 횟수'),
        ),
        migrations.AddField(
            model_name='brandsource',
            name='mapping_confidence',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='매핑 신뢰도'),
        ),
        migrations.AddField(
            model_name='brandsource',
            name='mapping_method',
            field=models.CharField(blank=True, choices=[('SOURCE_ID', '기존 Source ID'), ('EXACT_NAME', '이름 정확 일치'), ('NORMALIZED_NAME', '정규화 이름 일치'), ('ALIAS', '별칭 일치'), ('MANUAL', '수동 매핑')], max_length=30, null=True, verbose_name='매핑 방식'),
        ),
        migrations.AddField(
            model_name='brandsource',
            name='mapping_status',
            field=models.CharField(choices=[('UNMAPPED', '미매핑'), ('AUTO_MAPPED', '자동 매핑'), ('MANUAL_MAPPED', '수동 매핑'), ('REJECTED', '제외')], db_index=True, default='UNMAPPED', max_length=30, verbose_name='매핑 상태'),
        ),
        migrations.AddField(
            model_name='brandsource',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='정규화 플랫폼 브랜드명'),
        ),
        migrations.AddField(
            model_name='brandsource',
            name='normalized_name_en',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='정규화 플랫폼 영문 브랜드명'),
        ),
        migrations.AddField(
            model_name='brandsource',
            name='source_brand_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='플랫폼 영문 브랜드명'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_code',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='FEEDIT 브랜드 코드'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='영문 브랜드명'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='표준 브랜드명'),
        ),
        migrations.AlterField(
            model_name='brandsource',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_mappings', to='core.brand', verbose_name='표준 브랜드'),
        ),
        migrations.AlterField(
            model_name='brandsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='brandsource',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최초 발견일시'),
        ),
        migrations.AlterField(
            model_name='brandsource',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최근 발견일시'),
        ),
        migrations.AlterField(
            model_name='brandsource',
            name='source_brand_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='플랫폼 브랜드명'),
        ),
        migrations.AlterField(
            model_name='brandsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='termalias',
            name='alias_type',
            field=models.CharField(choices=[('SYNONYM', '동의어/유사어'), ('PLATFORM', '플랫폼 표기'), ('OCR', 'OCR 표기'), ('TYPO', '오탈자'), ('OTHER', '기타')], db_index=True, default='SYNONYM', max_length=30, verbose_name='별칭 유형'),
        ),
        migrations.AlterField(
            model_name='termalias',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='termalias',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='brandsource',
            index=models.Index(fields=['source', 'mapping_status'], name='idx_brand_source_status'),
        ),
        migrations.AddIndex(
            model_name='brandsource',
            index=models.Index(fields=['source', 'normalized_name'], name='idx_brand_source_name'),
        ),
        migrations.AddConstraint(
            model_name='brandsource',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_status__in', ['UNMAPPED', 'AUTO_MAPPED', 'MANUAL_MAPPED', 'REJECTED'])), name='ck_brand_source_mapping_status'),
        ),
        migrations.AddConstraint(
            model_name='brandsource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mapping_status__in', ['AUTO_MAPPED', 'MANUAL_MAPPED']), ('brand__isnull', False)), models.Q(('mapping_status__in', ['UNMAPPED', 'REJECTED']), ('brand__isnull', True)), _connector='OR'), name='ck_brand_source_mapping_consistency'),
        ),
        migrations.RemoveField(
            model_name='brandsource',
            name='is_official',
        ),
    ]
