# Generated by Django 6.1 on 2026-09-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_brandsource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='normalization_error',
            field=models.TextField(blank=True, null=True, verbose_name='정규화 오류'),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='normalization_status',
            field=models.CharField(choices=[('PENDING', '정규화 대기'), ('PROCESSING', '정규화 중'), ('SUCCESS', '성공'), ('FAILED', '실패')], db_index=True, default='PENDING', max_length=20, verbose_name='정규화 상태'),
        ),
        migrations.AddField(
            model_name='rawdocument',
            name='normalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='정규화 완료일시'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['normalization_status', 'id'], name='idx_rawdoc_norm_status'),
        ),
    ]
