# Generated by Django 6.1 on 2026-09-03 02:15

import apps.core.models.collection
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rawdocument_normalization_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrun',
            name='crawl_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_runs', to='core.crawltarget', verbose_name='수집 대상'),
        ),
        migrations.AlterField(
            model_name='crawltarget',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=1440, help_text='수집 주기(분). 기본값 1440분 = 24시간'),
        ),
        migrations.AlterField(
            model_name='crawltarget',
            name='params',
            field=models.JSONField(blank=True, default=apps.core.models.collection.default_crawl_target_params),
        ),
        migrations.AlterField(
            model_name='rawdocument',
            name='crawl_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_documents', to='core.crawlrun', verbose_name='수집 실행'),
        ),
    ]
