# Generated by Django 6.1 on 2026-09-03 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_crawlrun_crawl_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_category_id', models.CharField(max_length=255, verbose_name='플랫폼 카테고리 ID')),
                ('source_category_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='플랫폼 카테고리명')),
                ('source_category_path', models.TextField(blank=True, null=True, verbose_name='플랫폼 카테고리 경로')),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='정규화 카테고리명')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 관측일')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 관측일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '플랫폼 카테고리 매핑',
                'verbose_name_plural': '플랫폼 카테고리 매핑',
                'db_table': '"dictionary"."category_source"',
            },
        ),
        migrations.RemoveConstraint(
            model_name='categoryalias',
            name='uq_cat_alias_src',
        ),
        migrations.AddField(
            model_name='categorysource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_mappings', to='core.category', verbose_name='FEEDIT 표준 카테고리'),
        ),
        migrations.AddField(
            model_name='categorysource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sources', to='core.source', verbose_name='출처'),
        ),
        migrations.RemoveField(
            model_name='categoryalias',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryalias',
            name='source',
        ),
        migrations.AddIndex(
            model_name='categorysource',
            index=models.Index(fields=['source', 'source_category_id'], name='idx_cat_source_src_id'),
        ),
        migrations.AddIndex(
            model_name='categorysource',
            index=models.Index(fields=['source', 'normalized_name'], name='idx_cat_source_src_name'),
        ),
        migrations.AddIndex(
            model_name='categorysource',
            index=models.Index(fields=['category'], name='idx_cat_source_category'),
        ),
        migrations.AddConstraint(
            model_name='categorysource',
            constraint=models.UniqueConstraint(fields=('source', 'source_category_id'), name='uq_category_source_src_id'),
        ),
        migrations.AddConstraint(
            model_name='categorysource',
            constraint=models.CheckConstraint(condition=models.Q(('last_seen_at__isnull', True), ('first_seen_at__isnull', True), ('last_seen_at__gte', models.F('first_seen_at')), _connector='OR'), name='ck_category_source_seen'),
        ),
        migrations.DeleteModel(
            name='CategoryAlias',
        ),
    ]
