# Generated by Django 6.1 (makemigrations)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_crawlrun_crawl_target_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='termmetricdaily',
            name='uq_term_metric_day',
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='같은 축 안에서 이 용어가 어느 정도 위치인가', max_digits=5, null=True, verbose_name='수준(0~100)'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='ma28',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='28일 이동평균'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='ma7',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='7일 이동평균'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='metric_version',
            field=models.CharField(blank=True, db_index=True, default='', help_text='예: feedit-l2-v2-shadow', max_length=64, verbose_name='지표 버전'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='momentum',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='1보다 크면 최근 7일이 28일 평균보다 뜨겁다', max_digits=8, null=True, verbose_name='가속(ma7/ma28)'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='pct_rank',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='이름과 달리 0~1 이 아니라 0~100 이다. 크롤러 실측으로 확인했다.', max_digits=6, null=True, verbose_name='백분위(0~100)'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='source',
            field=models.ForeignKey(blank=True, help_text='비우면 전 플랫폼 합산', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_metrics', to='core.source', verbose_name='플랫폼'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='수준 60% + 가속 40%. 구간: ~25 차가움 ~50 미지근 ~75 따뜻함 이상 과열', max_digits=5, null=True, verbose_name='트렌드 온도(0~100)'),
        ),
        migrations.AlterField(
            model_name='termmetricdaily',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='raw_count · log_value · share_pct 등 정렬에 안 쓰는 값', verbose_name='추가 지표'),
        ),
        migrations.AddIndex(
            model_name='termmetricdaily',
            index=models.Index(fields=['metric_date', '-temp'], name='idx_term_metric_temp'),
        ),
        migrations.AddIndex(
            model_name='termmetricdaily',
            index=models.Index(fields=['metric_date', '-momentum'], name='idx_term_metric_mom'),
        ),
        migrations.AddIndex(
            model_name='termmetricdaily',
            index=models.Index(fields=['source', 'metric_date'], name='idx_term_metric_source'),
        ),
        migrations.AddConstraint(
            model_name='termmetricdaily',
            constraint=models.UniqueConstraint(fields=('term', 'source', 'metric_date', 'metric_version'), name='uq_term_metric_day', nulls_distinct=False),
        ),
    ]
