# Generated by Django 6.1 on 2026-09-03 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_categorysource_remove_categoryalias_uq_cat_alias_src_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsource',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sources', to='core.brand', verbose_name='표준 브랜드'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sources', to='core.category', verbose_name='표준 카테고리'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='detected_count',
            field=models.BigIntegerField(default=1, verbose_name='발견 횟수'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='mapping_status',
            field=models.CharField(choices=[('UNMAPPED', '상품 미매핑'), ('REVIEW', '검토 중'), ('MAPPED', '표준 상품 연결 완료'), ('REJECTED', '제외')], db_index=True, default='UNMAPPED', max_length=20, verbose_name='상품 매핑 상태'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='정규화 상품명'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='source_brand_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='플랫폼 브랜드 ID'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='source_category_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='플랫폼 카테고리 ID'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='source_category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='플랫폼 카테고리명'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='source_category_path',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='플랫폼 카테고리 경로'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='source_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='플랫폼 상품명'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True, verbose_name='대표 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='productsource',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='core.product', verbose_name='표준 상품'),
        ),
        migrations.AlterField(
            model_name='productsource',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성')], db_index=True, default='ACTIVE', max_length=20, verbose_name='상태'),
        ),
        migrations.AddIndex(
            model_name='productsource',
            index=models.Index(fields=['source', 'source_product_id'], name='idx_prod_src_lookup'),
        ),
        migrations.AddIndex(
            model_name='productsource',
            index=models.Index(fields=['brand'], name='idx_prod_src_brand'),
        ),
        migrations.AddIndex(
            model_name='productsource',
            index=models.Index(fields=['category'], name='idx_prod_src_cat'),
        ),
        migrations.AddIndex(
            model_name='productsource',
            index=models.Index(fields=['source', 'mapping_status'], name='idx_prod_src_map_status'),
        ),
    ]
