# Generated by Django 6.1 on 2026-09-03 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0030_productsource_brand_productsource_category_and_more",
        ),
    ]

    operations = [

        # ========================================================
        # 1. 이미 DB에서 사라진 기존 인덱스
        #    → Django migration state에서만 제거
        # ========================================================

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="productsource",
                    name="idx_prod_src_brand",
                ),
                migrations.RemoveIndex(
                    model_name="productsource",
                    name="idx_prod_src_cat",
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="productsource",
                    name="brand",
                ),
                migrations.RemoveField(
                    model_name="productsource",
                    name="category",
                ),
                migrations.RemoveField(
                    model_name="productsource",
                    name="source_brand_id",
                ),
                migrations.RemoveField(
                    model_name="productsource",
                    name="source_category_id",
                ),
                migrations.RemoveField(
                    model_name="productsource",
                    name="source_category_name",
                ),
                migrations.RemoveField(
                    model_name="productsource",
                    name="source_category_path",
                ),
            ],
        ),
        migrations.AddField(
            model_name="productsource",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="플랫폼 상품 속성",
            ),
        ),

        migrations.AddField(
            model_name="productsource",
            name="gender_scope",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="성별 범위",
            ),
        ),

        migrations.AddField(
            model_name="productsource",
            name="source_name_en",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="플랫폼 영문 상품명",
            ),
        ),

        migrations.AddField(
            model_name="productsource",
            name="style_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="스타일/모델 번호",
            ),
        ),

        # ========================================================
        # 5. 플랫폼 원본 BrandSource / CategorySource FK
        #
        # DB에는 새로:
        # source_brand_id BIGINT
        # source_category_id BIGINT
        # 가 생성됨
        # ========================================================

        migrations.AddField(
            model_name="productsource",
            name="source_brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_sources",
                to="core.brandsource",
                verbose_name="플랫폼 브랜드",
            ),
        ),

        migrations.AddField(
            model_name="productsource",
            name="source_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_sources",
                to="core.categorysource",
                verbose_name="플랫폼 카테고리",
            ),
        ),

        # ========================================================
        # 6. Mapping Status 문구 최종화
        # ========================================================

        migrations.AlterField(
            model_name="productsource",
            name="mapping_status",
            field=models.CharField(
                choices=[
                    (
                        "UNMAPPED",
                        "표준 상품 미매핑",
                    ),
                    (
                        "REVIEW",
                        "검토 중",
                    ),
                    (
                        "MAPPED",
                        "표준 상품 연결 완료",
                    ),
                    (
                        "REJECTED",
                        "제외",
                    ),
                ],
                db_index=True,
                default="UNMAPPED",
                max_length=20,
                verbose_name="상품 매핑 상태",
            ),
        ),

        # ========================================================
        # 7. 신규 FK / style index
        # ========================================================

        migrations.AddIndex(
            model_name="productsource",
            index=models.Index(
                fields=[
                    "source_brand",
                ],
                name="idx_prod_src_brand",
            ),
        ),

        migrations.AddIndex(
            model_name="productsource",
            index=models.Index(
                fields=[
                    "source_category",
                ],
                name="idx_prod_src_cat",
            ),
        ),

        migrations.AddIndex(
            model_name="productsource",
            index=models.Index(
                fields=[
                    "style_no",
                ],
                name="idx_prod_src_style",
            ),
        ),
    ]