# Generated by Django 6.1 on 2026-09-03 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0030_productsource_brand_productsource_category_and_more",
        ),
    ]

    operations = [

        # ========================================================
        # 1. 이미 DB에서 사라진 기존 인덱스
        #    → Django migration state에서만 제거
        # ========================================================

        # ★ 2026-09-23 — 운영 RDS 에서는 이 인덱스·컬럼이 이미 손으로 지워진 상태라
        #   state 만 고쳤었다(database_operations=[]). 그런데 **빈 DB 에서 처음부터**
        #   migrate 하면(테스트 DB · 새 개발 DB) 0030 이 만든 것이 그대로 남아,
        #   아래 source_brand FK(컬럼 source_brand_id)를 더할 때 DuplicateColumn 으로 멈췄다.
        #   IF EXISTS 로 지우므로 운영처럼 이미 없는 DB 에서는 아무 일도 하지 않는다.
        #   (운영 RDS 에는 이 마이그레이션이 이미 적용돼 있어 다시 돌지도 않는다.)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'DROP INDEX IF EXISTS "commerce"."idx_prod_src_brand"',
                        'DROP INDEX IF EXISTS "commerce"."idx_prod_src_cat"',
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="productsource",
                    name="idx_prod_src_brand",
                ),
                migrations.RemoveIndex(
                    model_name="productsource",
                    name="idx_prod_src_cat",
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'ALTER TABLE "commerce"."product_source" '
                        'DROP COLUMN IF EXISTS "brand_id", '
                        'DROP COLUMN IF EXISTS "category_id", '
                        'DROP COLUMN IF EXISTS "source_brand_id", '
                        'DROP COLUMN IF EXISTS "source_category_id", '
                        'DROP COLUMN IF EXISTS "source_category_name", '
                        'DROP COLUMN IF EXISTS "source_category_path"',
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="productsource",
                    name="brand",
                ),
                migrations.RemoveField(
                    model_name="productsource",
                    name="category",
                ),
                migrations.RemoveField(
                    model_name="productsource",
                    name="source_brand_id",
                ),
                migrations.RemoveField(
                    model_name="productsource",
                    name="source_category_id",
                ),
                migrations.RemoveField(
                    model_name="productsource",
                    name="source_category_name",
                ),
                migrations.RemoveField(
                    model_name="productsource",
                    name="source_category_path",
                ),
            ],
        ),
        migrations.AddField(
            model_name="productsource",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="플랫폼 상품 속성",
            ),
        ),

        migrations.AddField(
            model_name="productsource",
            name="gender_scope",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="성별 범위",
            ),
        ),

        migrations.AddField(
            model_name="productsource",
            name="source_name_en",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="플랫폼 영문 상품명",
            ),
        ),

        migrations.AddField(
            model_name="productsource",
            name="style_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="스타일/모델 번호",
            ),
        ),

        # ========================================================
        # 5. 플랫폼 원본 BrandSource / CategorySource FK
        #
        # DB에는 새로:
        # source_brand_id BIGINT
        # source_category_id BIGINT
        # 가 생성됨
        # ========================================================

        migrations.AddField(
            model_name="productsource",
            name="source_brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_sources",
                to="core.brandsource",
                verbose_name="플랫폼 브랜드",
            ),
        ),

        migrations.AddField(
            model_name="productsource",
            name="source_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_sources",
                to="core.categorysource",
                verbose_name="플랫폼 카테고리",
            ),
        ),

        # ========================================================
        # 6. Mapping Status 문구 최종화
        # ========================================================

        migrations.AlterField(
            model_name="productsource",
            name="mapping_status",
            field=models.CharField(
                choices=[
                    (
                        "UNMAPPED",
                        "표준 상품 미매핑",
                    ),
                    (
                        "REVIEW",
                        "검토 중",
                    ),
                    (
                        "MAPPED",
                        "표준 상품 연결 완료",
                    ),
                    (
                        "REJECTED",
                        "제외",
                    ),
                ],
                db_index=True,
                default="UNMAPPED",
                max_length=20,
                verbose_name="상품 매핑 상태",
            ),
        ),

        # ========================================================
        # 7. 신규 FK / style index
        # ========================================================

        migrations.AddIndex(
            model_name="productsource",
            index=models.Index(
                fields=[
                    "source_brand",
                ],
                name="idx_prod_src_brand",
            ),
        ),

        migrations.AddIndex(
            model_name="productsource",
            index=models.Index(
                fields=[
                    "source_category",
                ],
                name="idx_prod_src_cat",
            ),
        ),

        migrations.AddIndex(
            model_name="productsource",
            index=models.Index(
                fields=[
                    "style_no",
                ],
                name="idx_prod_src_style",
            ),
        ),
    ]