# Generated by Django 6.1 on 2026-09-06 23:27

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_productsource_idx_prod_src_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermCandidateObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('PRODUCT_NAME', '상품명'), ('PRODUCT_ATTRIBUTE', '상품 속성'), ('PRODUCT_DESCRIPTION', '상품 설명'), ('OCR', 'OCR'), ('VIDEO_TITLE', '영상 제목'), ('TRANSCRIPT', '영상 자막'), ('REVIEW', '리뷰'), ('COMMENT', '댓글'), ('OTHER', '기타')], db_index=True, max_length=30, verbose_name='발견 데이터 유형')),
                ('source_entity_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='원본 엔터티 ID')),
                ('detected_phrase', models.CharField(max_length=255, verbose_name='발견 표현')),
                ('raw_text', models.TextField(verbose_name='원본 문맥')),
                ('detected_at', models.DateTimeField(db_index=True, verbose_name='발견일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '용어 후보 관측',
                'verbose_name_plural': '용어 후보 관측',
                'db_table': '"dictionary"."term_candidate_observation"',
            },
        ),
        migrations.RemoveIndex(
            model_name='mappingcandidate',
            name='idx_mapping_type_status',
        ),
        migrations.RemoveIndex(
            model_name='mappingcandidate',
            name='idx_mapping_source_status',
        ),
        migrations.RemoveConstraint(
            model_name='mappingcandidate',
            name='uq_mapping_candidate',
        ),
        migrations.AlterModelOptions(
            name='categorysource',
            options={'verbose_name': '플랫폼 카테고리', 'verbose_name_plural': '플랫폼 카테고리'},
        ),
        migrations.AlterModelOptions(
            name='dictionaryterm',
            options={'verbose_name': '표준 용어', 'verbose_name_plural': '표준 용어'},
        ),
        migrations.AlterModelOptions(
            name='termcandidate',
            options={'verbose_name': '신규 용어 후보', 'verbose_name_plural': '신규 용어 후보'},
        ),
        migrations.RemoveConstraint(
            model_name='dictionaryterm',
            name='uq_dict_term_name',
        ),
        migrations.RemoveConstraint(
            model_name='termalias',
            name='uq_term_alias_global',
        ),
        migrations.RemoveConstraint(
            model_name='termalias',
            name='uq_term_alias_source',
        ),
        migrations.RemoveIndex(
            model_name='categorysource',
            name='idx_cat_source_src_name',
        ),
        migrations.RemoveIndex(
            model_name='termalias',
            name='idx_term_alias_norm',
        ),
        migrations.RemoveIndex(
            model_name='termalias',
            name='idx_term_alias_src_norm',
        ),
        migrations.RemoveIndex(
            model_name='termcandidate',
            name='idx_term_cand_norm',
        ),
        migrations.RemoveIndex(
            model_name='termcandidate',
            name='idx_term_cand_status',
        ),
        migrations.AddField(
            model_name='dictionaryterm',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='용어 임베딩'),
        ),
        migrations.AddField(
            model_name='dictionaryterm',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='임베딩 갱신일시'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='decision',
            field=models.CharField(choices=[('PENDING', '미판정'), ('NEW_TERM', '신규 표준 용어'), ('ALIAS', '기존 용어 별칭'), ('REJECT', '제외')], db_index=True, default='PENDING', max_length=20, verbose_name='판정'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='후보 임베딩'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='임베딩 갱신일시'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='nearest_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearest_candidates', to='core.dictionaryterm', verbose_name='가장 유사한 기존 용어'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='검토 메모'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='similarity_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='기존 용어 유사도'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='source_count',
            field=models.PositiveIntegerField(default=1, verbose_name='발견 출처 수'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='후보 신뢰도'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='detected_count',
            field=models.BigIntegerField(default=1, verbose_name='총 발견 횟수'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='status',
            field=models.CharField(choices=[('PENDING', '검토 대기'), ('REVIEWING', '검토 중'), ('RESOLVED', '처리 완료')], db_index=True, default='PENDING', max_length=20, verbose_name='처리 상태'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='suggested_type',
            field=models.CharField(blank=True, choices=[('BRAND', '브랜드'), ('STYLE', '스타일'), ('ITEM', '아이템'), ('DETAIL', '디테일'), ('MATERIAL', '소재'), ('COLOR', '색상'), ('TPO', 'TPO')], db_index=True, max_length=30, null=True, verbose_name='추천 용어 유형'),
        ),
        migrations.AddIndex(
            model_name='categorysource',
            index=models.Index(fields=['source', 'source_category_name'], name='idx_cat_source_name'),
        ),
        migrations.AddIndex(
            model_name='termalias',
            index=models.Index(fields=['alias'], name='idx_term_alias'),
        ),
        migrations.AddIndex(
            model_name='termalias',
            index=models.Index(fields=['source', 'alias'], name='idx_term_alias_source'),
        ),
        migrations.AddIndex(
            model_name='termcandidate',
            index=models.Index(fields=['raw_term', 'suggested_type'], name='idx_term_cand_raw_type'),
        ),
        migrations.AddIndex(
            model_name='termcandidate',
            index=models.Index(fields=['status', 'decision'], name='idx_term_cand_decision'),
        ),
        migrations.AddIndex(
            model_name='termcandidate',
            index=models.Index(fields=['suggested_type', '-detected_count'], name='idx_term_cand_type_count'),
        ),
        migrations.AddIndex(
            model_name='termcandidate',
            index=models.Index(fields=['-last_seen_at'], name='idx_term_cand_last_seen'),
        ),
        migrations.AddConstraint(
            model_name='dictionaryterm',
            constraint=models.UniqueConstraint(fields=('term_type', 'canonical_name'), name='uq_dict_term_name'),
        ),
        migrations.AddConstraint(
            model_name='termalias',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', True)), fields=('term', 'alias'), name='uq_term_alias_global'),
        ),
        migrations.AddConstraint(
            model_name='termalias',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False)), fields=('term', 'alias', 'source'), name='uq_term_alias_source'),
        ),
        migrations.AddField(
            model_name='termcandidateobservation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.termcandidate', verbose_name='용어 후보'),
        ),
        migrations.AddField(
            model_name='termcandidateobservation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_candidate_observations', to='core.source', verbose_name='출처'),
        ),
        migrations.RemoveField(
            model_name='mappingcandidate',
            name='source',
        ),
        migrations.RemoveField(
            model_name='dictionaryterm',
            name='normalized_name',
        ),
        migrations.RemoveField(
            model_name='categorysource',
            name='normalized_name',
        ),
        migrations.RemoveField(
            model_name='termalias',
            name='normalized_alias',
        ),
        migrations.RemoveField(
            model_name='termcandidate',
            name='detected_source',
        ),
        migrations.RemoveField(
            model_name='termcandidate',
            name='example_context',
        ),
        migrations.RemoveField(
            model_name='termcandidate',
            name='normalized_term',
        ),
        migrations.AddIndex(
            model_name='termcandidateobservation',
            index=models.Index(fields=['candidate', '-detected_at'], name='idx_term_obs_candidate'),
        ),
        migrations.AddIndex(
            model_name='termcandidateobservation',
            index=models.Index(fields=['source', 'source_type'], name='idx_term_obs_source'),
        ),
        migrations.DeleteModel(
            name='MappingCandidate',
        ),
    ]
