# Generated by Django 6.1 on 2026-09-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_termcandidateobservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termcandidate',
            name='suggested_attribute_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='추천 세부 속성 유형'),
        ),
    ]
