# Generated by Django 6.1 on 2026-09-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_termcandidate_suggested_attribute_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='termcandidate',
            name='decision_reason',
            field=models.TextField(blank=True, null=True, verbose_name='자동 판정 사유'),
        ),
    ]
