# Generated by Django 6.1 on 2026-09-07 10:11

import django.db.models.deletion

from django.db import migrations, models


# ============================================================
# DATA MIGRATION
# 기존 Brand의 NULL brand_code를 안전하게 채움
# ============================================================


def fill_missing_brand_codes(apps, schema_editor):

    Brand = apps.get_model(
        "core",
        "Brand",
    )

    # NULL
    for brand in Brand.objects.filter(
        brand_code__isnull=True
    ):

        base_code = (
            f"BRAND_LEGACY_{brand.pk}"
        )

        code = base_code
        suffix = 1

        while Brand.objects.filter(
            brand_code=code
        ).exclude(
            pk=brand.pk
        ).exists():

            code = (
                f"{base_code}_{suffix}"
            )

            suffix += 1

        brand.brand_code = code

        brand.save(
            update_fields=[
                "brand_code",
            ]
        )

    # 혹시 빈 문자열 데이터도 있으면 처리
    for brand in Brand.objects.filter(
        brand_code=""
    ):

        base_code = (
            f"BRAND_LEGACY_{brand.pk}"
        )

        code = base_code
        suffix = 1

        while Brand.objects.filter(
            brand_code=code
        ).exclude(
            pk=brand.pk
        ).exists():

            code = (
                f"{base_code}_{suffix}"
            )

            suffix += 1

        brand.brand_code = code

        brand.save(
            update_fields=[
                "brand_code",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0034_termcandidate_decision_reason",
        ),
    ]

    operations = [

        # ====================================================
        # BRAND SOURCE
        # 기존 제약/인덱스 정리
        # ====================================================

        migrations.AlterModelOptions(
            name="brandsource",
            options={},
        ),

        migrations.RemoveConstraint(
            model_name="brandsource",
            name="uq_brand_source_src_id",
        ),

        migrations.RemoveConstraint(
            model_name="brandsource",
            name="ck_brand_source_seen",
        ),

        migrations.RemoveConstraint(
            model_name="brandsource",
            name="ck_brand_source_mapping_status",
        ),

        migrations.RemoveConstraint(
            model_name="brandsource",
            name="ck_brand_source_mapping_consistency",
        ),

        migrations.RemoveIndex(
            model_name="brandsource",
            name="idx_brand_source_brand",
        ),

        migrations.RemoveIndex(
            model_name="brandsource",
            name="idx_brand_source_status",
        ),

        migrations.RemoveIndex(
            model_name="brandsource",
            name="idx_brand_source_name",
        ),

        # ====================================================
        # IMPORTANT
        # 기존 BrandSource 데이터 보존하면서 필드명 변경
        # ====================================================

        migrations.RenameField(
            model_name="brandsource",
            old_name="source_brand_name",
            new_name="name",
        ),

        migrations.RenameField(
            model_name="brandsource",
            old_name="source_brand_name_en",
            new_name="english_name",
        ),

        migrations.RenameField(
            model_name="brandsource",
            old_name="source_brand_url",
            new_name="source_profile_url",
        ),

        # ====================================================
        # BRAND 신규 필드
        # ====================================================

        migrations.AddField(
            model_name="brand",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="브랜드 대표 이미지 또는 로고",
                max_length=1000,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="brand",
            name="is_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    "관리자가 표준 브랜드 정보를 "
                    "검수했는지 여부"
                ),
            ),
        ),

        migrations.AddField(
            model_name="brand",
            name="source_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text=(
                    "현재 연결된 플랫폼 "
                    "BrandSource 수"
                ),
            ),
        ),

        migrations.AddField(
            model_name="brand",
            name="styles",
            field=models.ManyToManyField(
                blank=True,
                help_text="FEEDIT 표준 스타일",
                related_name="brands",
                to="core.style",
            ),
        ),

        migrations.AddField(
            model_name="brand",
            name="target_age",
            field=models.JSONField(
                blank=True,
                help_text=(
                    'ex) ["20", "25", "30"]'
                ),
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="brand",
            name="target_gender",
            field=models.JSONField(
                blank=True,
                help_text=(
                    'ex) ["WOMEN", '
                    '"MEN", "UNISEX"]'
                ),
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="brand",
            name="website_url",
            field=models.URLField(
                blank=True,
                max_length=1000,
                null=True,
            ),
        ),

        # ====================================================
        # BRAND SOURCE 신규 프로필 필드
        # ====================================================

        migrations.AddField(
            model_name="brandsource",
            name="attributes",
            field=models.JSONField(
                blank=True,
                help_text="플랫폼별 추가 원본 정보",
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="brandsource",
            name="country_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="brandsource",
            name="description",
            field=models.TextField(
                blank=True,
                help_text=(
                    "플랫폼에서 제공한 "
                    "브랜드 소개/문구"
                ),
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="brandsource",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text=(
                    "플랫폼에서 제공한 "
                    "대표 이미지/로고"
                ),
                max_length=1000,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="brandsource",
            name="styles",
            field=models.ManyToManyField(
                blank=True,
                related_name="brand_sources",
                to="core.style",
            ),
        ),

        migrations.AddField(
            model_name="brandsource",
            name="target_age",
            field=models.JSONField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="brandsource",
            name="target_gender",
            field=models.JSONField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="brandsource",
            name="website_url",
            field=models.URLField(
                blank=True,
                max_length=1000,
                null=True,
            ),
        ),

        # ====================================================
        # RENAMED FIELD 최종 속성
        # ====================================================

        migrations.AlterField(
            model_name="brandsource",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    "플랫폼에서 수집한 브랜드명"
                ),
                max_length=200,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="brandsource",
            name="english_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="brandsource",
            name="source_profile_url",
            field=models.URLField(
                blank=True,
                help_text=(
                    "플랫폼 브랜드/스토어 페이지"
                ),
                max_length=1000,
                null=True,
            ),
        ),

        # ====================================================
        # BRAND CODE NULL 먼저 해결
        # ====================================================

        migrations.RunPython(
            fill_missing_brand_codes,
            migrations.RunPython.noop,
        ),

        # ====================================================
        # BRAND 필드 변경
        # ====================================================

        migrations.AlterField(
            model_name="brand",
            name="brand_code",
            field=models.CharField(
                db_index=True,
                help_text=(
                    "FEEDIT 표준 브랜드 코드. "
                    "ex) BRAND_NIKE"
                ),
                max_length=100,
                unique=True,
            ),
        ),

        migrations.AlterField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "FEEDIT 브랜드 카테고리"
                ),
                limit_choices_to={
                    "category_type": "BRAND",
                },
                null=True,
                on_delete=(
                    django.db.models
                    .deletion.SET_NULL
                ),
                related_name="brands",
                to="core.category",
            ),
        ),

        migrations.AlterField(
            model_name="brand",
            name="country_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    "KR / US / JP / FR 등"
                ),
                max_length=10,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(
                blank=True,
                help_text=(
                    "브랜드 소개 / 컨셉 / 슬로건"
                ),
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="표준 브랜드명",
            ),
        ),

        # ====================================================
        # BRAND SOURCE 기존 필드 변경
        # ====================================================

        migrations.AlterField(
            model_name="brandsource",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=(
                    django.db.models
                    .deletion.SET_NULL
                ),
                related_name="brand_sources",
                to="core.brand",
            ),
        ),

        migrations.AlterField(
            model_name="brandsource",
            name="detected_count",
            field=models.PositiveIntegerField(
                default=0,
            ),
        ),

        migrations.AlterField(
            model_name="brandsource",
            name="first_seen_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="brandsource",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="brandsource",
            name="mapping_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="brandsource",
            name="mapping_method",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "SOURCE_ID",
                        "Source ID",
                    ),
                    (
                        "EXACT_NAME",
                        "정확 이름",
                    ),
                    (
                        "ALIAS",
                        "Alias",
                    ),
                    (
                        "SIMILARITY",
                        "유사도",
                    ),
                    (
                        "MANUAL",
                        "수동",
                    ),
                ],
                max_length=30,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="brandsource",
            name="mapping_status",
            field=models.CharField(
                choices=[
                    (
                        "UNMAPPED",
                        "미매핑",
                    ),
                    (
                        "AUTO_MAPPED",
                        "자동 매핑",
                    ),
                    (
                        "MANUAL_MAPPED",
                        "수동 매핑",
                    ),
                    (
                        "EXCLUDED",
                        "제외",
                    ),
                ],
                db_index=True,
                default="UNMAPPED",
                max_length=30,
            ),
        ),

        migrations.AlterField(
            model_name="brandsource",
            name="source",
            field=models.ForeignKey(
                on_delete=(
                    django.db.models
                    .deletion.CASCADE
                ),
                related_name="brand_sources",
                to="core.source",
            ),
        ),

        migrations.AlterField(
            model_name="brandsource",
            name="source_brand_id",
            field=models.CharField(
                help_text=(
                    "플랫폼 브랜드/스토어 "
                    "고유 ID"
                ),
                max_length=255,
            ),
        ),

        # ====================================================
        # 새 UNIQUE
        # ====================================================

        migrations.AddConstraint(
            model_name="brandsource",
            constraint=models.UniqueConstraint(
                fields=(
                    "source",
                    "source_brand_id",
                ),
                name=(
                    "uq_brand_source_"
                    "source_brand_id"
                ),
            ),
        ),

        # ====================================================
        # 진짜 버리는 필드
        # ====================================================

        migrations.RemoveField(
            model_name="brandsource",
            name="normalized_name",
        ),

        migrations.RemoveField(
            model_name="brandsource",
            name="normalized_name_en",
        ),
    ]