# Generated by Django 6.1 on 2026-09-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_brandsource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='상품 코드'),
        ),
    ]
