# Generated by Django 6.1 on 2026-09-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryterm',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='정규화 용어명'),
        ),
        migrations.AddField(
            model_name='termalias',
            name='normalized_alias',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='정규화 별칭'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='normalized_term',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='정규화 후보 용어'),
        ),
        migrations.AddField(
            model_name='termcandidateobservation',
            name='residual_text',
            field=models.TextField(blank=True, null=True, verbose_name='사전 매칭 제거 후 잔여 문맥'),
        ),
        migrations.AddField(
            model_name='termcandidateobservation',
            name='source_field',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='원본 필드'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='attribute_type',
            field=models.CharField(choices=[('FIT', '핏'), ('SILHOUETTE', '실루엣'), ('NECKLINE', '넥라인'), ('SLEEVE', '소매'), ('LENGTH', '기장'), ('DETAIL', '기타 디테일')], db_index=True, default='DETAIL', max_length=30, verbose_name='속성 유형'),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='term_type',
            field=models.CharField(choices=[('BRAND', '브랜드'), ('STYLE', '스타일'), ('ITEM', '아이템'), ('DETAIL', '디테일'), ('MATERIAL', '소재'), ('COLOR', '색상'), ('TPO', 'TPO')], db_index=True, max_length=30, verbose_name='용어 유형'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='detected_count',
            field=models.BigIntegerField(default=0, verbose_name='총 발견 횟수'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='source_count',
            field=models.PositiveIntegerField(default=0, verbose_name='발견 출처 수'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='status',
            field=models.CharField(choices=[('PENDING', '검토 대기'), ('REVIEWING', '검토 중'), ('RESOLVED', '처리 완료'), ('REJECTED', '제외')], db_index=True, default='PENDING', max_length=20, verbose_name='처리 상태'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='suggested_attribute_type',
            field=models.CharField(blank=True, choices=[('FIT', '핏'), ('SILHOUETTE', '실루엣'), ('NECKLINE', '넥라인'), ('SLEEVE', '소매'), ('LENGTH', '기장'), ('DETAIL', '기타 디테일')], db_index=True, max_length=30, null=True, verbose_name='추천 세부 속성 유형'),
        ),
        migrations.AddIndex(
            model_name='dictionaryterm',
            index=models.Index(fields=['term_type', 'normalized_name'], name='idx_dict_term_type_norm'),
        ),
        migrations.AddIndex(
            model_name='termalias',
            index=models.Index(fields=['normalized_alias'], name='idx_term_alias_norm'),
        ),
        migrations.AddIndex(
            model_name='termcandidate',
            index=models.Index(fields=['normalized_term', 'suggested_type'], name='idx_term_cand_norm_type'),
        ),
        migrations.AddIndex(
            model_name='termcandidateobservation',
            index=models.Index(fields=['source_type', 'source_field'], name='idx_term_obs_field'),
        ),
        migrations.AddIndex(
            model_name='termcandidateobservation',
            index=models.Index(fields=['source_type', 'source_entity_id'], name='idx_term_obs_entity'),
        ),
    ]
