# Generated by Django 6.1 on 2026-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_dictionaryterm_normalized_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dictionaryterm',
            name='uq_dict_term_name',
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='정규화 용어명'),
        ),
        migrations.AlterField(
            model_name='termalias',
            name='normalized_alias',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='정규화 별칭'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='normalized_term',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='정규화 후보 용어'),
        ),
        migrations.AddConstraint(
            model_name='dictionaryterm',
            constraint=models.UniqueConstraint(fields=('term_type', 'normalized_name'), name='uq_dict_term_name'),
        ),
    ]
