# Generated by Django 6.1 on 2026-09-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_dictionaryterm_uq_dict_term_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_product_item',
        ),
        migrations.AddField(
            model_name='product',
            name='english_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='영문 상품명'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.style', verbose_name='스타일'),
        ),
        migrations.AddField(
            model_name='productsourcesnapshot',
            name='sales_count',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='판매 수'),
        ),
        migrations.AddField(
            model_name='productsourcesnapshot',
            name='view_count',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='조회 수'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='표준 상품 속성'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category', verbose_name='표준 카테고리'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성')], db_index=True, default='ACTIVE', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='productsourcesnapshot',
            name='observed_at',
            field=models.DateTimeField(db_index=True, verbose_name='관측일시'),
        ),
        migrations.AlterField(
            model_name='resalesnapshot',
            name='observed_at',
            field=models.DateTimeField(db_index=True, verbose_name='관측일시'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['style'], name='idx_product_style'),
        ),
        migrations.AddIndex(
            model_name='productsourcesnapshot',
            index=models.Index(fields=['product_source', '-observed_at'], name='idx_prod_snap_prod_time'),
        ),
        migrations.AddIndex(
            model_name='productterm',
            index=models.Index(fields=['product'], name='idx_prod_term_product'),
        ),
        migrations.AddIndex(
            model_name='productterm',
            index=models.Index(fields=['term'], name='idx_prod_term_term'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_term',
        ),
    ]
