# Generated by Django 6.1 on 2026-09-08 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_product_idx_product_item_product_english_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to='core.dictionaryterm', verbose_name='용어')),
                ('person_type', models.CharField(choices=[('CELEBRITY', '연예인'), ('INFLUENCER', '인플루언서'), ('CREATOR', '크리에이터'), ('OTHER', '기타')], db_index=True, default='OTHER', max_length=30, verbose_name='인물 유형')),
                ('gender', models.CharField(choices=[('M', '남성'), ('W', '여성'), ('NON_BINARY', '논바이너리'), ('UNKNOWN', '미상')], db_index=True, default='UNKNOWN', max_length=20, verbose_name='성별')),
                ('profile_url', models.URLField(blank=True, help_text='Instagram, YouTube, TikTok 등 대표 프로필 URL', max_length=1000, null=True, verbose_name='대표 프로필 URL')),
                ('social_urls', models.JSONField(blank=True, default=dict, help_text='예: {"instagram": "...", "youtube": "...", "tiktok": "..."}', verbose_name='소셜 URL')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '인물',
                'verbose_name_plural': '인물',
                'db_table': '"dictionary"."person"',
            },
        ),
        migrations.RemoveConstraint(
            model_name='dictionaryterm',
            name='ck_dict_term_type',
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='term_type',
            field=models.CharField(choices=[('BRAND', '브랜드'), ('STYLE', '스타일'), ('ITEM', '아이템'), ('DETAIL', '디테일'), ('MATERIAL', '소재'), ('COLOR', '색상'), ('TPO', 'TPO'), ('PERSON', '인물')], db_index=True, max_length=30, verbose_name='용어 유형'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='suggested_type',
            field=models.CharField(blank=True, choices=[('BRAND', '브랜드'), ('STYLE', '스타일'), ('ITEM', '아이템'), ('DETAIL', '디테일'), ('MATERIAL', '소재'), ('COLOR', '색상'), ('TPO', 'TPO'), ('PERSON', '인물')], db_index=True, max_length=30, null=True, verbose_name='추천 용어 유형'),
        ),
        migrations.AddConstraint(
            model_name='dictionaryterm',
            constraint=models.CheckConstraint(condition=models.Q(('term_type__in', ['BRAND', 'STYLE', 'ITEM', 'DETAIL', 'MATERIAL', 'COLOR', 'TPO', 'PERSON'])), name='ck_dict_term_type'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['person_type'], name='idx_person_type'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['gender'], name='idx_person_gender'),
        ),
    ]
