# Generated by Django 6.1 on 2026-09-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_person_remove_dictionaryterm_ck_dict_term_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile_url',
        ),
        migrations.RemoveField(
            model_name='person',
            name='social_urls',
        ),
        migrations.AddField(
            model_name='contentprofile',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_profiles', to='core.person', verbose_name='FEEDIT 인물'),
        ),
        migrations.AddField(
            model_name='person',
            name='image_url',
            field=models.URLField(blank=True, help_text='FEEDIT에서 사용하는 인물 대표 이미지', max_length=1000, null=True, verbose_name='대표 이미지'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('W', '여성'), ('MIXED', '혼성'), ('UNKNOWN', '미상')], db_index=True, default='UNKNOWN', max_length=20, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='person',
            name='term',
            field=models.OneToOneField(limit_choices_to={'term_type': 'PERSON'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to='core.dictionaryterm', verbose_name='인물 용어'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
