# Generated by Django 6.1 on 2026-09-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_person_profile_url_remove_person_social_urls_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='color',
            name='ck_color_self_base',
        ),
        migrations.AddField(
            model_name='color',
            name='color_mood',
            field=models.CharField(blank=True, choices=[('PASTEL', '파스텔'), ('VIVID', '비비드'), ('DEEP_DARK', '딥/다크'), ('MUTED', '뮤트'), ('LIGHT', '라이트')], db_index=True, max_length=20, null=True, verbose_name='색감 특성'),
        ),
        migrations.AddField(
            model_name='color',
            name='color_tone',
            field=models.CharField(blank=True, choices=[('WARM', '웜톤'), ('COOL', '쿨톤'), ('NEUTRAL', '뉴트럴')], db_index=True, max_length=20, null=True, verbose_name='톤'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_family',
            field=models.CharField(choices=[('BLACK', '블랙'), ('WHITE', '화이트'), ('GRAY', '그레이'), ('BEIGE', '베이지'), ('BROWN', '브라운'), ('RED', '레드'), ('ORANGE', '오렌지'), ('YELLOW', '옐로우'), ('GREEN', '그린'), ('BLUE', '블루'), ('PURPLE', '퍼플'), ('PINK', '핑크'), ('METALLIC', '메탈릭'), ('ETC', '기타')], db_index=True, default='ETC', max_length=30, verbose_name='색상 계열'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='attribute_type',
            field=models.CharField(choices=[('PATTERN', '패턴'), ('FIT', '핏'), ('SILHOUETTE', '실루엣'), ('LENGTH', '기장'), ('SHAPE', '형태/쉐입'), ('NECKLINE', '넥라인/카라'), ('SLEEVE', '소매'), ('POCKET', '포켓'), ('CLOSURE', '여밈'), ('DECORATION', '장식'), ('ETC', '기타')], db_index=True, default='ETC', max_length=30, verbose_name='속성 유형'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='term',
            field=models.OneToOneField(limit_choices_to={'term_type': 'DETAIL'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='core.dictionaryterm', verbose_name='용어'),
        ),
        migrations.AlterField(
            model_name='termcandidate',
            name='suggested_attribute_type',
            field=models.CharField(blank=True, choices=[('PATTERN', '패턴'), ('FIT', '핏'), ('SILHOUETTE', '실루엣'), ('LENGTH', '기장'), ('SHAPE', '형태/쉐입'), ('NECKLINE', '넥라인/카라'), ('SLEEVE', '소매'), ('POCKET', '포켓'), ('CLOSURE', '여밈'), ('DECORATION', '장식'), ('ETC', '기타')], db_index=True, max_length=30, null=True, verbose_name='추천 세부 속성 유형'),
        ),
        migrations.AlterField(
            model_name='tpo',
            name='term',
            field=models.OneToOneField(limit_choices_to={'term_type': 'TPO'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tpo', serialize=False, to='core.dictionaryterm', verbose_name='용어'),
        ),
        migrations.AlterField(
            model_name='tpo',
            name='tpo_type',
            field=models.CharField(choices=[('OCCASION', '행사/상황'), ('ACTIVITY', '활동'), ('PLACE', '장소'), ('TIME', '시간대'), ('SEASON', '계절/시기'), ('ETC', '기타')], db_index=True, default='ETC', max_length=30, verbose_name='TPO 유형'),
        ),
    ]
