# Generated by Django 6.1 on 2026-09-09 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_color_ck_color_self_base_color_color_mood_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productterm',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='productterm',
            name='uq_product_term',
        ),
        migrations.RemoveIndex(
            model_name='productterm',
            name='idx_prod_term_product',
        ),
        migrations.RemoveIndex(
            model_name='productterm',
            name='idx_prod_term_term',
        ),
        migrations.AddField(
            model_name='productterm',
            name='product_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_terms', to='core.productsource', verbose_name='소스 상품'),
        ),
        migrations.AddIndex(
            model_name='productterm',
            index=models.Index(fields=['product_source'], name='idx_prod_term_source'),
        ),
        migrations.AddConstraint(
            model_name='productterm',
            constraint=models.UniqueConstraint(fields=('product_source', 'term'), name='uq_prodsrc_term'),
        ),
        migrations.RemoveField(
            model_name='productterm',
            name='product',
        ),
    ]
