# Generated by Django 6.1 on 2026-09-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_productterm_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productsourcesnapshot',
            name='uq_prod_snapshot',
        ),
        migrations.RemoveIndex(
            model_name='termcandidate',
            name='idx_term_cand_raw_type',
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='document_count',
            field=models.BigIntegerField(default=0, verbose_name='발견 문서 수'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='evidence_s3_uri',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='후보 관측 근거 S3 경로'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='evidence_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='후보 근거 갱신일시'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='field_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='필드별 발견 통계'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='sample_contexts',
            field=models.JSONField(blank=True, default=list, verbose_name='대표 관측 문맥'),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='source_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='출처별 발견 통계'),
        ),
        migrations.AddConstraint(
            model_name='productsourcesnapshot',
            constraint=models.UniqueConstraint(fields=('product_source', 'observed_at', 'ranking_scope'), name='uq_prod_snapshot_scope'),
        ),
        migrations.AddConstraint(
            model_name='termcandidate',
            constraint=models.UniqueConstraint(fields=('normalized_term', 'suggested_type'), name='uq_term_candidate_norm_type'),
        ),
    ]
