# Generated by Django 6.1 on 2026-09-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_productsourcesnapshot_uq_prod_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='제외 용어')),
                ('normalized_term', models.CharField(db_index=True, max_length=255, verbose_name='정규화 제외 용어')),
                ('reason', models.CharField(choices=[('GENERIC', '일반 문맥어'), ('GENDER', '성별 메타'), ('CATEGORY', '카테고리 표현'), ('PRODUCT_META', '상품 메타'), ('MARKETING', '마케팅 표현'), ('SEASON', '시즌 표현'), ('OTHER', '기타')], db_index=True, max_length=30, verbose_name='제외 사유')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성 여부')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, help_text='비어 있으면 모든 출처에 적용', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovery_exclusions', to='core.source', verbose_name='출처')),
            ],
            options={
                'verbose_name': '제외 사전',
                'verbose_name_plural': '제외 사전',
                'db_table': '"dictionary"."discovery_exclusion"',
                'indexes': [models.Index(fields=['normalized_term', 'is_active'], name='idx_disc_excl_norm_active'), models.Index(fields=['source', 'normalized_term'], name='idx_disc_excl_source_norm'), models.Index(fields=['reason', 'is_active'], name='idx_disc_excl_reason')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source__isnull', True)), fields=('normalized_term',), name='uq_discovery_exclusion_global'), models.UniqueConstraint(condition=models.Q(('source__isnull', False)), fields=('normalized_term', 'source'), name='uq_discovery_exclusion_source')],
            },
        ),
    ]
