# Generated by Django 6.1 on 2026-09-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_discoveryexclusion'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="termcandidate",
                    name="uq_term_candidate_norm_type",
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name='termcandidate',
            name='idx_term_cand_norm_type',
        ),
        migrations.AddIndex(
            model_name='termcandidate',
            index=models.Index(fields=['normalized_term'], name='idx_term_cand_norm'),
        ),
        migrations.AddConstraint(
            model_name='termcandidate',
            constraint=models.UniqueConstraint(fields=('normalized_term',), name='uq_term_candidate_norm'),
        ),
    ]
