# Generated by Django 6.1 on 2026-09-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0046_remove_termcandidate_uq_term_candidate_norm_type_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE dictionary.term_candidate
                    ADD COLUMN IF NOT EXISTS document_count
                    BIGINT NOT NULL DEFAULT 0;

                    ALTER TABLE dictionary.term_candidate
                    ADD COLUMN IF NOT EXISTS source_breakdown
                    JSONB NOT NULL DEFAULT '{}'::jsonb;

                    ALTER TABLE dictionary.term_candidate
                    ADD COLUMN IF NOT EXISTS field_breakdown
                    JSONB NOT NULL DEFAULT '{}'::jsonb;

                    ALTER TABLE dictionary.term_candidate
                    ADD COLUMN IF NOT EXISTS sample_contexts
                    JSONB NOT NULL DEFAULT '[]'::jsonb;

                    ALTER TABLE dictionary.term_candidate
                    ADD COLUMN IF NOT EXISTS evidence_s3_uri
                    VARCHAR(1024);

                    ALTER TABLE dictionary.term_candidate
                    ADD COLUMN IF NOT EXISTS evidence_updated_at
                    TIMESTAMPTZ;

                    ALTER TABLE dictionary.term_candidate
                    ALTER COLUMN document_count DROP DEFAULT;

                    ALTER TABLE dictionary.term_candidate
                    ALTER COLUMN source_breakdown DROP DEFAULT;

                    ALTER TABLE dictionary.term_candidate
                    ALTER COLUMN field_breakdown DROP DEFAULT;

                    ALTER TABLE dictionary.term_candidate
                    ALTER COLUMN sample_contexts DROP DEFAULT;
                    """,
                    reverse_sql="""
                    ALTER TABLE dictionary.term_candidate
                    DROP COLUMN IF EXISTS evidence_updated_at;

                    ALTER TABLE dictionary.term_candidate
                    DROP COLUMN IF EXISTS evidence_s3_uri;

                    ALTER TABLE dictionary.term_candidate
                    DROP COLUMN IF EXISTS sample_contexts;

                    ALTER TABLE dictionary.term_candidate
                    DROP COLUMN IF EXISTS field_breakdown;

                    ALTER TABLE dictionary.term_candidate
                    DROP COLUMN IF EXISTS source_breakdown;

                    ALTER TABLE dictionary.term_candidate
                    DROP COLUMN IF EXISTS document_count;
                    """,
                ),
            ],
            state_operations=[],
        ),
    ]