# Generated by Django 6.1 on 2026-09-13 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0047_add_term_candidate_discovery_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveBigIntegerField(db_index=True, verbose_name='대상 ID')),
                ('pipeline', models.CharField(choices=[('NORMALIZATION', '상품 정규화'), ('CONTENT', '콘텐츠 분석'), ('VISION', '비전 분석'), ('TERM_DISCOVERY', '용어 발굴'), ('METRIC', '지표 계산')], db_index=True, default='NORMALIZATION', max_length=40)),
                ('task_type', models.CharField(choices=[('PREPROCESS', '기본 정규화'), ('ENTITY_NORMALIZE', '엔터티 정규화'), ('ATTRIBUTE_EXTRACT', '속성 추출'), ('DICTIONARY_MATCH', '사전 매칭'), ('TERM_CANDIDATE', '신규 용어 후보'), ('PRODUCT_PROMOTE', 'Product 승격'), ('OCR', 'OCR'), ('VISION', 'Vision 분석'), ('EMBEDDING', 'Embedding 생성'), ('CONTENT_ANALYSIS', '콘텐츠 분석'), ('TREND_METRIC', '트렌드 지표 계산')], db_index=True, max_length=50)),
                ('stage', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('status', models.CharField(choices=[('BLOCKED', '이전 단계 대기'), ('READY', '실행 가능'), ('RUNNING', '실행 중'), ('REVIEW', '검토 필요'), ('COMPLETED', '완료'), ('FAILED', '실패'), ('SKIPPED', '건너뜀')], db_index=True, default='BLOCKED', max_length=20)),
                ('requires_review', models.BooleanField(default=False, help_text='이 Task 유형이 REVIEW 상태를 가질 수 있는지 여부')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('input_s3_uri', models.TextField(blank=True, default='')),
                ('output_s3_uri', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crawl_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.crawlrun', verbose_name='수집 실행')),
                ('previous_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_tasks', to='core.task', verbose_name='이전 Task')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_processing_tasks', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='대상 타입')),
            ],
            options={
                'db_table': '"collection"."task"',
                'ordering': ['stage', 'id'],
                'indexes': [models.Index(fields=['pipeline', 'task_type', 'status'], name='idx_task_pipe_type_status'), models.Index(fields=['crawl_run', 'stage'], name='idx_task_crawl_stage'), models.Index(fields=['target_content_type', 'target_object_id'], name='idx_task_target')],
                'constraints': [models.UniqueConstraint(fields=('crawl_run', 'target_content_type', 'target_object_id', 'pipeline', 'task_type'), name='uq_task_run_target_pipe_type')],
            },
        ),
    ]
