# Generated by Django 6.1 on 2026-09-14
#
# FEEDIT 0049 recovery migration
#
# 실제 DB와 Django migration state가 어긋난 상태를 복구한다.
#
# 이미 DB에 존재하는 TermMetricDaily 컬럼:
# - level
# - ma7
# - ma28
# - metric_version
# - momentum
# - source_id
#
# DB에 기존 이름으로 존재:
# - pct_rank -> percentile
# - temp     -> trend_temperature

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_task"),
    ]

    operations = [

        # ============================================================
        # TextTermMention 신규 생성
        # ============================================================

        migrations.CreateModel(
            name="TextTermMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mention_text",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="언급 문맥",
                    ),
                ),
                (
                    "mention_role",
                    models.CharField(
                        choices=[
                            ("TARGET", "주요 대상"),
                            ("CONTEXT", "문맥 언급"),
                            ("COMPARISON", "비교 대상"),
                        ],
                        default="CONTEXT",
                        max_length=20,
                        verbose_name="언급 역할",
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        verbose_name="감성 점수",
                    ),
                ),
                (
                    "intent_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="구매 의도",
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        verbose_name="추출 신뢰도",
                    ),
                ),
                (
                    "start_seconds",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="시작 시점",
                    ),
                ),
                (
                    "end_seconds",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="종료 시점",
                    ),
                ),
                (
                    "analysis_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="추가 분석 정보",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="생성일시",
                    ),
                ),
            ],
            options={
                "verbose_name": "텍스트 용어 언급",
                "verbose_name_plural": "텍스트 용어 언급",
                "db_table": '"analysis"."text_term_mention"',
            },
        ),

        # ============================================================
        # 기존 Constraint / Index 정리
        # ============================================================

        migrations.RemoveConstraint(
            model_name="termassocdaily",
            name="uq_term_assoc_day",
        ),

        migrations.RemoveConstraint(
            model_name="termmetricdaily",
            name="uq_term_metric_day",
        ),

        migrations.RemoveIndex(
            model_name="termassocdaily",
            name="idx_assoc_score",
        ),

        migrations.RemoveIndex(
            model_name="termmetricdaily",
            name="idx_term_metric_trend",
        ),

        # DB 상태가 달라도 안전하게 처리:
        # - old index 있으면 rename
        # - new index 이미 있으면 noop
        # - 둘 다 없으면 새로 생성
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('analysis.idx_term_metric_term') IS NOT NULL THEN
                            ALTER INDEX analysis.idx_term_metric_term
                            RENAME TO idx_metric_term_day;
                        ELSIF to_regclass('analysis.idx_metric_term_day') IS NULL THEN
                            CREATE INDEX idx_metric_term_day
                            ON analysis.term_metric_daily
                            (term_id, metric_date DESC);
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="termmetricdaily",
                    new_name="idx_metric_term_day",
                    old_name="idx_term_metric_term",
                ),
            ],
        ),

        # ============================================================
        # TextDocument 분석 결과 분리
        # ============================================================

        migrations.RemoveField(
            model_name="textdocument",
            name="extracted_terms",
        ),

        migrations.RemoveField(
            model_name="textdocument",
            name="intent_code",
        ),

        migrations.RemoveField(
            model_name="textdocument",
            name="sentiment_score",
        ),

        # ============================================================
        # TermAssocDaily 신규 필드
        # ============================================================

        migrations.AddField(
            model_name="termassocdaily",
            name="association_percentile",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="연관도 백분위",
            ),
        ),

        migrations.AddField(
            model_name="termassocdaily",
            name="association_rank",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="연관 순위",
            ),
        ),

        migrations.AddField(
            model_name="termassocdaily",
            name="is_new",
            field=models.BooleanField(
                default=False,
                verbose_name="신규 연관",
            ),
        ),

        migrations.AddField(
            model_name="termassocdaily",
            name="lift",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=12,
                null=True,
                verbose_name="Lift",
            ),
        ),

        migrations.AddField(
            model_name="termassocdaily",
            name="metric_version",
            field=models.CharField(
                default="feedit-l2-v1",
                max_length=50,
                verbose_name="지표 버전",
            ),
        ),

        migrations.AddField(
            model_name="termassocdaily",
            name="pmi",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=12,
                null=True,
                verbose_name="PMI",
            ),
        ),

        # ============================================================
        # TermMetricDaily - 실제 DB에 아직 없는 신규 컬럼
        # ============================================================

        migrations.AddField(
            model_name="termmetricdaily",
            name="content_count",
            field=models.BigIntegerField(
                default=0,
                verbose_name="콘텐츠 수",
            ),
        ),

        migrations.AddField(
            model_name="termmetricdaily",
            name="creator_count",
            field=models.BigIntegerField(
                default=0,
                verbose_name="크리에이터 수",
            ),
        ),

        migrations.AddField(
            model_name="termmetricdaily",
            name="log_count",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=12,
                null=True,
                verbose_name="로그 보정값",
            ),
        ),

        migrations.AddField(
            model_name="termmetricdaily",
            name="negative_count",
            field=models.BigIntegerField(
                default=0,
                verbose_name="부정 의도 수",
            ),
        ),

        migrations.AddField(
            model_name="termmetricdaily",
            name="positive_count",
            field=models.BigIntegerField(
                default=0,
                verbose_name="긍정 의도 수",
            ),
        ),

        migrations.AddField(
            model_name="termmetricdaily",
            name="purchase_intent_index",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=7,
                null=True,
                verbose_name="구매의도 지수",
            ),
        ),

        migrations.AddField(
            model_name="termmetricdaily",
            name="raw_count",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="원시 신호",
            ),
        ),

        # ============================================================
        # 이미 DB에 존재하는 컬럼 -> state only
        #   ★ 2026-09-23 — 운영 RDS 에는 이미 있지만 빈 DB(테스트 DB 등)에는 없다.
        #     IF NOT EXISTS 로 만들어 두 경우 모두 맞춘다.
        # ============================================================

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        """
                        ALTER TABLE analysis.term_metric_daily
                            ADD COLUMN IF NOT EXISTS level numeric(7,4) NULL,
                            ADD COLUMN IF NOT EXISTS ma28 numeric(10,4) NULL,
                            ADD COLUMN IF NOT EXISTS ma7 numeric(10,4) NULL,
                            ADD COLUMN IF NOT EXISTS metric_version varchar(50) NOT NULL DEFAULT 'feedit-l2-v1',
                            ADD COLUMN IF NOT EXISTS momentum numeric(7,4) NULL,
                            ADD COLUMN IF NOT EXISTS source_id bigint NULL
                                REFERENCES collection.source(id) ON DELETE CASCADE
                                DEFERRABLE INITIALLY DEFERRED
                        """,
                        "CREATE INDEX IF NOT EXISTS term_metric_daily_source_id_idx "
                        "ON analysis.term_metric_daily (source_id)",
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="termmetricdaily",
                    name="level",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=7,
                        null=True,
                        verbose_name="화제성 레벨",
                    ),
                ),
                migrations.AddField(
                    model_name="termmetricdaily",
                    name="ma28",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="28일 이동평균",
                    ),
                ),
                migrations.AddField(
                    model_name="termmetricdaily",
                    name="ma7",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="7일 이동평균",
                    ),
                ),
                migrations.AddField(
                    model_name="termmetricdaily",
                    name="metric_version",
                    field=models.CharField(
                        default="feedit-l2-v1",
                        max_length=50,
                        verbose_name="지표 버전",
                    ),
                ),
                migrations.AddField(
                    model_name="termmetricdaily",
                    name="momentum",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=7,
                        null=True,
                        verbose_name="성장 모멘텀",
                    ),
                ),
                migrations.AddField(
                    model_name="termmetricdaily",
                    name="source",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_daily_metrics",
                        to="core.source",
                        verbose_name="플랫폼",
                    ),
                ),
            ],
        ),

        # ============================================================
        # pct_rank -> percentile
        # ============================================================

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'analysis'
                              AND table_name = 'term_metric_daily'
                              AND column_name = 'pct_rank'
                        ) AND NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'analysis'
                              AND table_name = 'term_metric_daily'
                              AND column_name = 'percentile'
                        ) THEN
                            ALTER TABLE analysis.term_metric_daily
                            RENAME COLUMN pct_rank TO percentile;
                        ELSIF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'analysis'
                              AND table_name = 'term_metric_daily'
                              AND column_name = 'percentile'
                        ) THEN
                            -- 2026-09-23: 빈 DB(테스트 DB 등)에는 옛 컬럼도 없다 → 새로 만든다
                            ALTER TABLE analysis.term_metric_daily
                            ADD COLUMN percentile numeric(7,4) NULL;
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="termmetricdaily",
                    name="percentile",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=7,
                        null=True,
                        verbose_name="플랫폼 내 백분위",
                    ),
                ),
            ],
        ),

        # ============================================================
        # temp -> trend_temperature
        # ============================================================

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'analysis'
                              AND table_name = 'term_metric_daily'
                              AND column_name = 'temp'
                        ) AND NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'analysis'
                              AND table_name = 'term_metric_daily'
                              AND column_name = 'trend_temperature'
                        ) THEN
                            ALTER TABLE analysis.term_metric_daily
                            RENAME COLUMN temp TO trend_temperature;
                        ELSIF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'analysis'
                              AND table_name = 'term_metric_daily'
                              AND column_name = 'trend_temperature'
                        ) THEN
                            -- 2026-09-23: 빈 DB(테스트 DB 등)에는 옛 컬럼도 없다 → 새로 만든다
                            ALTER TABLE analysis.term_metric_daily
                            ADD COLUMN trend_temperature numeric(7,4) NULL;
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="termmetricdaily",
                    name="trend_temperature",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=7,
                        null=True,
                        verbose_name="트렌드 온도",
                    ),
                ),
            ],
        ),

        # ============================================================
        # 기존 필드 속성 변경
        # ============================================================

        migrations.AlterField(
            model_name="termassocdaily",
            name="cooccurrence_count",
            field=models.BigIntegerField(
                default=0,
                verbose_name="동시 언급 문서 수",
            ),
        ),

        migrations.AlterField(
            model_name="textdocument",
            name="analysis_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="분석 메타데이터",
            ),
        ),

        # ============================================================
        # 신규 Index
        # ============================================================

        migrations.AddIndex(
            model_name="termassocdaily",
            index=models.Index(
                fields=["metric_date", "-pmi"],
                name="idx_assoc_pmi",
            ),
        ),

        migrations.AddIndex(
            model_name="termassocdaily",
            index=models.Index(
                fields=["source_term", "association_rank"],
                name="idx_assoc_src_rank",
            ),
        ),

        migrations.AddIndex(
            model_name="termmetricdaily",
            index=models.Index(
                fields=["metric_date", "-trend_temperature"],
                name="idx_metric_temp_day",
            ),
        ),

        migrations.AddIndex(
            model_name="termmetricdaily",
            index=models.Index(
                fields=["source", "metric_date"],
                name="idx_metric_source_day",
            ),
        ),

        migrations.AddIndex(
            model_name="textdocument",
            index=models.Index(
                fields=["source", "document_type"],
                name="idx_text_doc_source_type",
            ),
        ),

        # ============================================================
        # 신규 Unique Constraints
        # ============================================================

        migrations.AddConstraint(
            model_name="termassocdaily",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_term",
                    "target_term",
                    "metric_date",
                    "metric_version",
                ),
                name="uq_term_assoc_day_ver",
            ),
        ),

        migrations.AddConstraint(
            model_name="termmetricdaily",
            constraint=models.UniqueConstraint(
                fields=(
                    "term",
                    "source",
                    "metric_date",
                    "metric_version",
                ),
                name="uq_term_metric_source_day_ver",
            ),
        ),

        # ============================================================
        # TextTermMention FK
        # ============================================================

        migrations.AddField(
            model_name="texttermmention",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="term_mentions",
                to="core.textdocument",
                verbose_name="분석 문서",
            ),
        ),

        migrations.AddField(
            model_name="texttermmention",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_mentions",
                to="core.dictionaryterm",
                verbose_name="용어",
            ),
        ),

        # ============================================================
        # 기존 더 이상 사용하지 않는 컬럼 제거
        # ============================================================

        migrations.RemoveField(
            model_name="termassocdaily",
            name="association_score",
        ),

        migrations.RemoveField(
            model_name="termassocdaily",
            name="confidence",
        ),

        migrations.RemoveField(
            model_name="termmetricdaily",
            name="growth_rate",
        ),

        migrations.RemoveField(
            model_name="termmetricdaily",
            name="source_count",
        ),

        migrations.RemoveField(
            model_name="termmetricdaily",
            name="trend_score",
        ),

        # ============================================================
        # TextTermMention Index
        # ============================================================

        migrations.AddIndex(
            model_name="texttermmention",
            index=models.Index(
                fields=["document", "term"],
                name="idx_mention_doc_term",
            ),
        ),

        migrations.AddIndex(
            model_name="texttermmention",
            index=models.Index(
                fields=["term"],
                name="idx_mention_term",
            ),
        ),

        migrations.AddIndex(
            model_name="texttermmention",
            index=models.Index(
                fields=["term", "mention_role"],
                name="idx_mention_term_role",
            ),
        ),
    ]
