# Generated by Django 6.1 on 2026-09-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_texttermmention_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='termmetricdaily',
            name='uq_term_metric_source_day_ver',
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='chitchat_count',
            field=models.BigIntegerField(default=0, verbose_name='잡담 반응 수'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='critique_count',
            field=models.BigIntegerField(default=0, verbose_name='비판 반응 수'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='critique_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='비판 반응 비율'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='experience_count',
            field=models.BigIntegerField(default=0, verbose_name='경험 반응 수'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='experience_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='경험 반응 비율'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='negative_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='부정 반응 비율'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='neutral_count',
            field=models.BigIntegerField(default=0, verbose_name='중립 반응 수'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='neutral_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='중립 반응 비율'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='positive_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='긍정 반응 비율'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='praise_count',
            field=models.BigIntegerField(default=0, verbose_name='호평 반응 수'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='praise_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='호평 반응 비율'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='purchase_count',
            field=models.BigIntegerField(default=0, verbose_name='구매 반응 수'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='purchase_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='구매 반응 비율'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='question_count',
            field=models.BigIntegerField(default=0, verbose_name='질문 반응 수'),
        ),
        migrations.AddField(
            model_name='termmetricdaily',
            name='question_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='질문 반응 비율'),
        ),
        migrations.AlterField(
            model_name='termmetricdaily',
            name='negative_count',
            field=models.BigIntegerField(default=0, verbose_name='부정 반응 수'),
        ),
        migrations.AlterField(
            model_name='termmetricdaily',
            name='positive_count',
            field=models.BigIntegerField(default=0, verbose_name='긍정 반응 수'),
        ),
        migrations.AddConstraint(
            model_name='termmetricdaily',
            constraint=models.UniqueConstraint(fields=('term', 'source', 'metric_date', 'metric_version'), name='uq_term_metric_source_day_ver', nulls_distinct=False),
        ),
    ]
