# Generated by Django 6.1 on 2026-09-14 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_termmetricdaily_uq_term_metric_source_day_ver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermSearchMetricMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_month', models.DateField()),
                ('search_volume', models.BigIntegerField(default=0)),
                ('data_type', models.CharField(default='monthly_absolute', max_length=50)),
                ('metric_version', models.CharField(default='feedit-search-v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.source')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_metrics', to='core.dictionaryterm')),
            ],
            options={
                'db_table': '"analysis"."term_search_metric_monthly"',
                'constraints': [models.UniqueConstraint(fields=('term', 'source', 'metric_month', 'metric_version'), name='uq_term_search_month_source_ver')],
            },
        ),
    ]
