# Generated by Django 6.1 on 2026-09-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_termsearchmetricmonthly'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='termsearchmetricmonthly',
            name='uq_term_search_month_source_ver',
        ),
        migrations.AddField(
            model_name='termsearchmetricmonthly',
            name='log_volume',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='termsearchmetricmonthly',
            name='percentile',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='termsearchmetricmonthly',
            name='metric_month',
            field=models.DateField(verbose_name='기준 월'),
        ),
        migrations.AlterField(
            model_name='termsearchmetricmonthly',
            name='search_volume',
            field=models.BigIntegerField(default=0, verbose_name='월간 검색량'),
        ),
        migrations.AlterField(
            model_name='termsearchmetricmonthly',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_search_metric_monthly', to='core.source', verbose_name='검색 플랫폼'),
        ),
        migrations.AlterField(
            model_name='termsearchmetricmonthly',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_metric_monthly', to='core.dictionaryterm', verbose_name='용어'),
        ),
        migrations.AddIndex(
            model_name='termsearchmetricmonthly',
            index=models.Index(fields=['metric_month', '-search_volume'], name='idx_search_month_volume'),
        ),
        migrations.AddIndex(
            model_name='termsearchmetricmonthly',
            index=models.Index(fields=['term', '-metric_month'], name='idx_search_term_month'),
        ),
        migrations.AddConstraint(
            model_name='termsearchmetricmonthly',
            constraint=models.UniqueConstraint(fields=('term', 'source', 'metric_month', 'metric_version'), name='uq_term_search_month_ver'),
        ),
    ]
