# Generated by Django 6.1 on 2026-09-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_termsearchmetricmonthly_uq_term_search_month_source_ver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='ad_disclosure',
            field=models.CharField(blank=True, choices=[('DISCLOSED', '광고 표기'), ('AFFILIATE', '제휴 수수료'), ('NONE', '표기 없음')], db_index=True, default='', max_length=20, verbose_name='광고 표기'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='content_format',
            field=models.CharField(blank=True, choices=[('HAUL', '하울'), ('REVIEW', '리뷰'), ('RECOMMEND', '추천'), ('VERDICT', '살까말까'), ('STYLING', '코디'), ('VLOG', '브이로그'), ('ETC', '기타')], db_index=True, default='', max_length=20, verbose_name='영상 형식'),
        ),
    ]
