# Generated by Django 5.2.17 on 2026-09-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_votefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaveditem',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 알림 시각'),
        ),
        migrations.AddField(
            model_name='usersaveditem',
            name='notified_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='마지막 알림 가격'),
        ),
        migrations.AddField(
            model_name='usersaveditem',
            name='saved_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='찜 시점 가격'),
        ),
        migrations.AddField(
            model_name='usersaveditem',
            name='saved_price_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='찜 시점 가격 관측일시'),
        ),
        migrations.AddField(
            model_name='usersaveditem',
            name='saved_price_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_price_items', to='core.productsource', verbose_name='가격 기준 판매처'),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='전체 알림')),
                ('price_drop', models.BooleanField(default=True, verbose_name='찜한 상품 가격 하락')),
                ('vote_result', models.BooleanField(default=True, verbose_name='살!말? 투표 결과')),
                ('weekly_report', models.BooleanField(default=True, verbose_name='주간 트렌드 리포트')),
                ('badge', models.BooleanField(default=True, verbose_name='뱃지 달성')),
                ('term_added', models.BooleanField(default=True, verbose_name='용어 사전 등재')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to='core.appuser', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정',
                'db_table': '"app"."notification_setting"',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PRICE_DROP', '찜한 상품 가격 하락'), ('VOTE_RESULT', '살!말? 투표 결과'), ('WEEKLY_REPORT', '주간 트렌드 리포트'), ('BADGE', '뱃지 달성'), ('TERM_ADDED', '용어 사전 등재')], max_length=30, verbose_name='알림 종류')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('body', models.CharField(blank=True, default='', max_length=500, verbose_name='본문')),
                ('link', models.CharField(blank=True, default='', max_length=200, verbose_name='이동 화면')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='알림 근거')),
                ('dedup_key', models.CharField(max_length=200, verbose_name='중복 방지 키')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.appuser', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'db_table': '"app"."notification"',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_noti_user_time'), models.Index(fields=['user', 'read_at'], name='idx_noti_user_read')],
                'constraints': [models.UniqueConstraint(fields=('user', 'dedup_key'), name='uq_notification_user_key')],
            },
        ),
        migrations.CreateModel(
            name='TermRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_term', models.CharField(max_length=100, verbose_name='요청 용어')),
                ('normalized_term', models.CharField(max_length=100, verbose_name='정규화 이름')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='요청 메모')),
                ('status', models.CharField(choices=[('PENDING', '검토 대기'), ('ADDED', '등재됨'), ('REJECTED', '반려')], default='PENDING', max_length=20, verbose_name='처리 상태')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.dictionaryterm', verbose_name='등재된 용어')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_requests', to='core.appuser', verbose_name='요청자')),
            ],
            options={
                'verbose_name': '용어 등재 요청',
                'verbose_name_plural': '용어 등재 요청',
                'db_table': '"app"."term_request"',
                'indexes': [models.Index(fields=['status', 'normalized_term'], name='idx_term_req_status')],
                'constraints': [models.UniqueConstraint(fields=('user', 'normalized_term'), name='uq_term_request_user_term')],
            },
        ),
    ]
