# Generated by Django 5.2.17 on 2026-09-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_notification_term_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='지운 시각'),
        ),
    ]
