# Generated by Django 6.1 on 2026-09-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_notification_vote_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_review_id', models.CharField(max_length=100)),
                ('review_type', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('goods_option', models.CharField(max_length=200)),
                ('like_count', models.IntegerField()),
                ('reviewer_sex', models.CharField(max_length=20)),
                ('reviewer_height', models.IntegerField(blank=True, null=True)),
                ('reviewer_weight', models.IntegerField(blank=True, null=True)),
                ('survey', models.JSONField(default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"commerce"."product_review"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('document_count', models.BigIntegerField(default=0)),
                ('analyzed_document_count', models.BigIntegerField(default=0)),
                ('kept_document_count', models.BigIntegerField(default=0)),
                ('mention_count', models.BigIntegerField(default=0)),
                ('candidate_count', models.BigIntegerField(default=0)),
                ('analysis_coverage_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('evidence_valid_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('positive_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('negative_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('purchase_intent_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('metric_version', models.CharField(default='feedit-platform-v1', max_length=64)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"analysis"."platform_metric_daily"',
            },
        ),
        migrations.AddField(
            model_name='textdocument',
            name='analysis_version',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='분석 버전'),
        ),
        migrations.AddField(
            model_name='textdocument',
            name='product_source',
            field=models.ForeignKey(blank=True, help_text='커머스 리뷰가 귀속되는 실제 플랫폼 상품', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_documents', to='core.productsource', verbose_name='소스 상품'),
        ),
        migrations.AddField(
            model_name='textdocument',
            name='source_payload_hash',
            field=models.CharField(blank=True, db_index=True, help_text='원문이 바뀐 경우에만 재분석하기 위한 SHA-256', max_length=64, null=True, verbose_name='원문 해시'),
        ),
        migrations.AddField(
            model_name='textdocument',
            name='source_published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='수집일이 아니라 댓글·리뷰가 실제 작성된 시각', null=True, verbose_name='원문 작성일시'),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE analysis.text_document
                   SET source_published_at =
                       (analysis_metadata->>'published_at')::timestamptz
                 WHERE source_published_at IS NULL
                   AND analysis_metadata->>'published_at'
                       ~ '^\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}'
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='texttermmention',
            name='analysis_version',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='분석 버전'),
        ),
        migrations.AddField(
            model_name='texttermmention',
            name='evidence_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='근거 끝 문자 위치'),
        ),
        migrations.AddField(
            model_name='texttermmention',
            name='evidence_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='근거 시작 문자 위치'),
        ),
        migrations.AddField(
            model_name='texttermmention',
            name='evidence_status',
            field=models.CharField(choices=[('EXACT', 'LLM 근거와 원문이 정확히 일치'), ('EXPANDED', '검증 후 같은 문장 안에서 확장'), ('INVALID', '근거 검증 실패'), ('LEGACY', '기존 데이터')], db_index=True, default='LEGACY', max_length=20, verbose_name='근거 검증 상태'),
        ),
        migrations.AlterField(
            model_name='texttermmention',
            name='mention_role',
            field=models.CharField(choices=[('TARGET', '주요 대상'), ('CONTEXT', '문맥 언급'), ('COMPARISON', '비교 대상'), ('COMMENT', '유튜브 댓글'), ('REVIEW', '커머스 리뷰')], default='CONTEXT', max_length=20, verbose_name='언급 역할'),
        ),
        migrations.AddConstraint(
            model_name='texttermmention',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('evidence_end__isnull', True), ('evidence_start__isnull', True)),
                    models.Q(('evidence_end__gt', models.F('evidence_start')), ('evidence_start__isnull', False)),
                    _connector='OR',
                ),
                name='ck_mention_evidence_range',
            ),
        ),
        migrations.CreateModel(
            name='AnalysisPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True, verbose_name='기준일')),
                ('pipeline_version', models.CharField(db_index=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', '실행 중'), ('SUCCESS', '성공'), ('PARTIAL', '일부 성공'), ('FAILED', '실패')], db_index=True, default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_count', models.BigIntegerField(default=0)),
                ('analyzed_count', models.BigIntegerField(default=0)),
                ('skipped_count', models.BigIntegerField(default=0)),
                ('failure_count', models.BigIntegerField(default=0)),
                ('prompt_tokens', models.BigIntegerField(default=0)),
                ('cached_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_pipeline_runs', to='core.source', verbose_name='플랫폼')),
            ],
            options={
                'db_table': '"analysis"."pipeline_run"',
            },
        ),
        migrations.AddField(
            model_name='textdocument',
            name='analysis_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.analysispipelinerun', verbose_name='분석 실행'),
        ),
        migrations.AddIndex(
            model_name='textdocument',
            index=models.Index(fields=['product_source', 'document_type'], name='idx_text_doc_product'),
        ),
        migrations.AddIndex(
            model_name='textdocument',
            index=models.Index(fields=['source', 'analysis_version', 'analysis_status'], name='idx_text_doc_anl_ver'),
        ),
        migrations.AddConstraint(
            model_name='textdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('source', 'document_type', 'external_id'), name='uq_text_doc_source_type_external'),
        ),
        migrations.AddField(
            model_name='platformmetricdaily',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_daily_metrics', to='core.source'),
        ),
        migrations.AddIndex(
            model_name='analysispipelinerun',
            index=models.Index(fields=['-run_date', 'status'], name='idx_pipeline_run_day_status'),
        ),
        migrations.AddIndex(
            model_name='platformmetricdaily',
            index=models.Index(fields=['metric_date', 'source'], name='idx_platform_metric_day_src'),
        ),
        migrations.AddConstraint(
            model_name='platformmetricdaily',
            constraint=models.UniqueConstraint(fields=('source', 'metric_date', 'metric_version'), name='uq_platform_metric_day_ver'),
        ),
    ]
