# Generated by Django 6.1 on 2026-09-25 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_term_assoc_basis"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserXp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(default=0, verbose_name="누적 경험치"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="마지막 계산 시각"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_snapshot",
                        to="core.appuser",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "경험치 스냅숏",
                "verbose_name_plural": "경험치 스냅숏",
                "db_table": '"app"."user_xp"',
            },
        ),
        migrations.CreateModel(
            name="SiteFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("REQUEST", "불편사항·추가요청"),
                            ("BUG", "수정사항·버그리포트"),
                        ],
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "page",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="남긴 화면"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "확인 전"),
                            ("DONE", "반영·처리"),
                            ("REJECTED", "반려"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "admin_note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="운영자 메모",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_feedbacks",
                        to="core.appuser",
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "홈페이지 피드백",
                "verbose_name_plural": "홈페이지 피드백",
                "db_table": '"app"."site_feedback"',
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_site_feedback_user"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="idx_site_feedback_status",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserDailyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="날짜(KST)")),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="처음 접속한 시각"
                    ),
                ),
                (
                    "analysis_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="트렌드 분석 체류(초)"
                    ),
                ),
                (
                    "analysis_ping_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="체류 시간을 실제 흐른 시간보다 부풀리지 못하게 막는 기준점이다.",
                        null=True,
                        verbose_name="마지막 체류 기록 시각",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_activities",
                        to="core.appuser",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "일일 접속 기록",
                "verbose_name_plural": "일일 접속 기록",
                "db_table": '"app"."user_daily_activity"',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "day"), name="uq_daily_activity_user_day"
                    )
                ],
            },
        ),
    ]
