# Generated by Django 6.1 on 2026-09-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_xp_leveling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PRICE_DROP", "찜한 상품 가격 하락"),
                    ("VOTE_RESULT", "살!말? 투표 결과"),
                    ("WEEKLY_REPORT", "주간 트렌드 리포트"),
                    ("BADGE", "뱃지 달성"),
                    ("TERM_ADDED", "용어 사전 등재"),
                    ("JOB_REVIEW", "직업 인증 결과"),
                    ("VOTE_COMMENT", "살!말? 새 댓글"),
                    ("OPS_ALERT", "운영 알림"),
                ],
                max_length=30,
                verbose_name="알림 종류",
            ),
        ),
    ]
