# 모델과 마이그레이션 기록 맞추기 (2026-10-04)
#
#   [파이프라인 연동](4b21c9c) 때 모델 파일을 파이프라인 쪽 정의로 바꿨는데
#   마이그레이션이 따라오지 않아 `makemigrations --check` 가 실패하고 있었다.
#   (실수로 빠졌던 서비스 쪽 필드 — 찜 가격 · 검색량 · 분석 문서 · 브랜드 스타일 —
#   는 모델에 되살렸으므로 여기서는 지우지 않는다.)
#
#   ★ 운영 DB 상태를 모르는 채로 써야 했다. 파이프라인 쪽에서 이미 만든 테이블·칼럼이
#     있을 수 있으므로(예: Ko Hyun-A 0058/0059 의 product_source_relation)
#     DB 작업은 전부 "없으면 만든다" 로만 한다. 칼럼·데이터를 지우는 작업은 없다.
#       - 테이블 · 칼럼 · 인덱스      IF NOT EXISTS
#       - 제약                        이름으로 확인 후 추가. 기존 행이 어기면 건너뛰고 NOTICE
#       - ck_dict_term_type           TARGET 이 들어간 정의로 교체(기존 값의 상위 집합)
#       - uq_prodsrc_term             (상품, 용어) → (상품, 용어, 관계유형) 으로 교체.
#                                     옛 제약이 남아 있으면 관계유형별 저장이 막힌다.
#   ★ ProductReview
#       0062 가 "이미 있는 표(Ko Hyun-A 0054)" 로 보고 managed=False 로 적었는데 모델은
#       관리 대상이다. 그래서 빈 DB(CI)에는 표가 아예 없었다. 0054 와 같은 정의로
#       없을 때만 만든다.
#   ★ 상태에서만 빼고 DB 에는 남겨 두는 것
#       - 스냅숏 옛 유니크(uq_prod_snapshot_scope · uq_resale_snap)와 observed_at 인덱스.
#         일 단위 새 제약보다 느슨해 충돌하지 않고, 서비스 쿼리(최근 가격 등)가
#         아직 observed_at 인덱스를 탄다.
#
#   적용 전 확인:
#     python manage.py makemigrations --check --dry-run   → No changes detected
#     python manage.py sqlmigrate core 0071

import django.db.models.deletion
from django.db import migrations, models


def _add_constraint(table: str, name: str, definition: str) -> str:
    """이름이 없을 때만 제약을 건다. 기존 행이 어기면 건너뛰고 NOTICE 를 남긴다."""
    return f"""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = '{name}' AND conrelid = '{table}'::regclass
    ) THEN
        BEGIN
            ALTER TABLE {table} ADD CONSTRAINT "{name}" {definition};
        EXCEPTION WHEN unique_violation OR check_violation THEN
            RAISE NOTICE '0071: % 제약을 걸지 못했습니다 — 기존 행이 어깁니다', '{name}';
        END;
    END IF;
END $$;"""


DATABASE_SQL = "\n".join([
    # ── 새 테이블 ──────────────────────────────────────────
    """
CREATE TABLE IF NOT EXISTS "commerce"."product_source_relation" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "relation_type" varchar(50) NOT NULL,
    "evidence_source" varchar(100) NULL,
    "created_at" timestamp with time zone NOT NULL,
    "from_product_source_id" bigint NOT NULL
        REFERENCES "commerce"."product_source" ("id") DEFERRABLE INITIALLY DEFERRED,
    "to_product_source_id" bigint NOT NULL
        REFERENCES "commerce"."product_source" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS "commerce"."product_term_relation" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "relation_type" varchar(30) NOT NULL,
    "evidence_text" varchar(500) NOT NULL,
    "confidence" double precision NULL,
    "created_at" timestamp with time zone NOT NULL,
    "product_source_id" bigint NOT NULL
        REFERENCES "commerce"."product_source" ("id") DEFERRABLE INITIALLY DEFERRED,
    "subject_term_id" bigint NOT NULL
        REFERENCES "dictionary"."dictionary_term" ("id") DEFERRABLE INITIALLY DEFERRED,
    "object_term_id" bigint NOT NULL
        REFERENCES "dictionary"."dictionary_term" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS "dictionary"."target" (
    "term_id" bigint NOT NULL PRIMARY KEY
        REFERENCES "dictionary"."dictionary_term" ("id") DEFERRABLE INITIALLY DEFERRED,
    "target_type" varchar(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS "dictionary"."brand_product_categories" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "brand_id" bigint NOT NULL
        REFERENCES "dictionary"."brand" ("id") DEFERRABLE INITIALLY DEFERRED,
    "category_id" bigint NOT NULL
        REFERENCES "dictionary"."category" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS "dictionary"."brand_terms" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "brand_id" bigint NOT NULL
        REFERENCES "dictionary"."brand" ("id") DEFERRABLE INITIALLY DEFERRED,
    "dictionaryterm_id" bigint NOT NULL
        REFERENCES "dictionary"."dictionary_term" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS "commerce"."product_review" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "product_source_id" bigint NOT NULL
        REFERENCES "commerce"."product_source" ("id") DEFERRABLE INITIALLY DEFERRED,
    "source_review_id" varchar(100) NOT NULL,
    "review_type" varchar(30) NOT NULL,
    "content" text NOT NULL,
    "grade" integer NULL,
    "goods_option" varchar(200) NOT NULL,
    "like_count" integer NOT NULL,
    "reviewer_sex" varchar(20) NOT NULL,
    "reviewer_height" integer NULL,
    "reviewer_weight" integer NULL,
    "survey" jsonb NOT NULL,
    "source_created_at" timestamp with time zone NULL,
    "created_at" timestamp with time zone NOT NULL
);
CREATE TABLE IF NOT EXISTS "commerce"."product_styles" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "product_id" bigint NOT NULL
        REFERENCES "commerce"."product" ("id") DEFERRABLE INITIALLY DEFERRED,
    "style_id" bigint NOT NULL
        REFERENCES "dictionary"."style" ("term_id") DEFERRABLE INITIALLY DEFERRED
);""",
    # ── 새 칼럼 (전부 NULL 허용이거나 기본값이 있어 기존 행에 안전) ──
    """
ALTER TABLE "dictionary"."brand" ADD COLUMN IF NOT EXISTS "price_tier" varchar(20) NULL;
ALTER TABLE "commerce"."product" ADD COLUMN IF NOT EXISTS "group_key" varchar(150) NULL;
ALTER TABLE "commerce"."product_source" ADD COLUMN IF NOT EXISTS "season" varchar(50) NULL;
ALTER TABLE "commerce"."product_source" ADD COLUMN IF NOT EXISTS "season_year" smallint NULL CHECK ("season_year" >= 0);
ALTER TABLE "commerce"."product_source" ADD COLUMN IF NOT EXISTS "sell_end_at" timestamp with time zone NULL;
ALTER TABLE "commerce"."product_source" ADD COLUMN IF NOT EXISTS "sell_start_at" timestamp with time zone NULL;
-- 기본값 '[]' 은 남겨 둔다. ORM 밖(SQL 직접 적재)에서 넣는 행도 NOT NULL 을 지키게 된다.
ALTER TABLE "commerce"."product_source" ADD COLUMN IF NOT EXISTS "source_genders" jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE "snapshot"."product_source_snapshot" ADD COLUMN IF NOT EXISTS "snapshot_date" date NULL;
ALTER TABLE "commerce"."product_term" ADD COLUMN IF NOT EXISTS "relation_type" varchar(32) NULL;
ALTER TABLE "snapshot"."resale_snapshot" ADD COLUMN IF NOT EXISTS "snapshot_date" date NULL;""",
    # ── 교체되는 제약 ─────────────────────────────────────
    """
ALTER TABLE "dictionary"."dictionary_term" DROP CONSTRAINT IF EXISTS "ck_dict_term_type";
ALTER TABLE "commerce"."product_term" DROP CONSTRAINT IF EXISTS "uq_prodsrc_term";
-- 0068 이 근거 칼럼을 지울 때 함께 사라졌다. 남아 있는 DB 를 위한 정리일 뿐이다.
ALTER TABLE "analysis"."text_term_mention" DROP CONSTRAINT IF EXISTS "ck_mention_evidence_range";""",
    _add_constraint(
        '"dictionary"."dictionary_term"', "ck_dict_term_type",
        "CHECK (\"term_type\" IN ('BRAND', 'STYLE', 'ITEM', 'DETAIL', 'MATERIAL', "
        "'COLOR', 'TPO', 'PERSON', 'TARGET'))",
    ),
    _add_constraint(
        '"snapshot"."product_source_snapshot"', "uq_prod_snapshot_daily_scope",
        'UNIQUE ("product_source_id", "snapshot_date", "ranking_scope")',
    ),
    _add_constraint(
        '"commerce"."product_term"', "uq_prodsrc_term_relation",
        'UNIQUE ("product_source_id", "term_id", "relation_type")',
    ),
    _add_constraint(
        '"snapshot"."resale_snapshot"', "uq_resale_daily",
        'UNIQUE ("product_source_id", "snapshot_date")',
    ),
    _add_constraint(
        '"commerce"."product_source_relation"', "uq_product_source_relation",
        'UNIQUE ("from_product_source_id", "to_product_source_id", "relation_type")',
    ),
    _add_constraint(
        '"commerce"."product_review"', "uq_product_review_source_review",
        'UNIQUE ("product_source_id", "source_review_id")',
    ),
    _add_constraint(
        '"commerce"."product_term_relation"', "uq_prod_term_relation",
        'UNIQUE ("product_source_id", "subject_term_id", "relation_type", "object_term_id")',
    ),
    _add_constraint(
        '"commerce"."product_term_relation"', "ck_prod_term_rel_not_self",
        'CHECK (NOT ("subject_term_id" = ("object_term_id")))',
    ),
    _add_constraint(
        '"dictionary"."brand_product_categories"',
        "brand_product_categories_brand_id_category_id_e661837e_uniq",
        'UNIQUE ("brand_id", "category_id")',
    ),
    _add_constraint(
        '"dictionary"."brand_terms"',
        "brand_terms_brand_id_dictionaryterm_id_082da011_uniq",
        'UNIQUE ("brand_id", "dictionaryterm_id")',
    ),
    _add_constraint(
        '"commerce"."product_styles"',
        "product_styles_product_id_style_id_e11d75b1_uniq",
        'UNIQUE ("product_id", "style_id")',
    ),
    # ── 인덱스 (이름은 Django 가 만드는 이름과 같다) ──────────────
    """
CREATE INDEX IF NOT EXISTS "idx_product_group" ON "commerce"."product" ("brand_id", "group_key");
CREATE INDEX IF NOT EXISTS "idx_prod_snap_date" ON "snapshot"."product_source_snapshot" ("snapshot_date" DESC, "observed_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_prod_snap_prod_date" ON "snapshot"."product_source_snapshot" ("product_source_id", "snapshot_date" DESC);
CREATE INDEX IF NOT EXISTS "idx_prod_term_relation" ON "commerce"."product_term" ("relation_type", "term_id");
CREATE INDEX IF NOT EXISTS "idx_resale_date_index" ON "snapshot"."resale_snapshot" ("snapshot_date" DESC, "resale_index" DESC);
CREATE INDEX IF NOT EXISTS "idx_resale_prod_date" ON "snapshot"."resale_snapshot" ("product_source_id", "snapshot_date" DESC);
CREATE INDEX IF NOT EXISTS "idx_prod_src_rel_from" ON "commerce"."product_source_relation" ("from_product_source_id", "relation_type");
CREATE INDEX IF NOT EXISTS "idx_prod_src_rel_to" ON "commerce"."product_source_relation" ("to_product_source_id", "relation_type");
CREATE INDEX IF NOT EXISTS "idx_ptr_product" ON "commerce"."product_term_relation" ("product_source_id");
CREATE INDEX IF NOT EXISTS "idx_ptr_subject_rel" ON "commerce"."product_term_relation" ("subject_term_id", "relation_type");
CREATE INDEX IF NOT EXISTS "idx_ptr_object_rel" ON "commerce"."product_term_relation" ("object_term_id", "relation_type");
CREATE INDEX IF NOT EXISTS "idx_ptr_prod_subject" ON "commerce"."product_term_relation" ("product_source_id", "subject_term_id");
CREATE INDEX IF NOT EXISTS "product_term_relation_relation_type_9c204193" ON "commerce"."product_term_relation" ("relation_type");
CREATE INDEX IF NOT EXISTS "product_term_relation_relation_type_9c204193_like" ON "commerce"."product_term_relation" ("relation_type" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "brand_price_tier_25b37b89" ON "dictionary"."brand" ("price_tier");
CREATE INDEX IF NOT EXISTS "brand_price_tier_25b37b89_like" ON "dictionary"."brand" ("price_tier" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "brand_product_categories_brand_id_583f9b05" ON "dictionary"."brand_product_categories" ("brand_id");
CREATE INDEX IF NOT EXISTS "brand_product_categories_category_id_15eb9fe6" ON "dictionary"."brand_product_categories" ("category_id");
CREATE INDEX IF NOT EXISTS "brand_terms_brand_id_fd9adcdc" ON "dictionary"."brand_terms" ("brand_id");
CREATE INDEX IF NOT EXISTS "brand_terms_dictionaryterm_id_27f3c3e8" ON "dictionary"."brand_terms" ("dictionaryterm_id");
CREATE INDEX IF NOT EXISTS "product_group_key_09d20b5b" ON "commerce"."product" ("group_key");
CREATE INDEX IF NOT EXISTS "product_group_key_09d20b5b_like" ON "commerce"."product" ("group_key" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "product_styles_product_id_319f8dcb" ON "commerce"."product_styles" ("product_id");
CREATE INDEX IF NOT EXISTS "product_styles_style_id_98e4d4d1" ON "commerce"."product_styles" ("style_id");
CREATE INDEX IF NOT EXISTS "product_source_season_d02163c0" ON "commerce"."product_source" ("season");
CREATE INDEX IF NOT EXISTS "product_source_season_d02163c0_like" ON "commerce"."product_source" ("season" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "product_source_season_year_6195044b" ON "commerce"."product_source" ("season_year");
CREATE INDEX IF NOT EXISTS "product_source_sell_end_at_91a9eb07" ON "commerce"."product_source" ("sell_end_at");
CREATE INDEX IF NOT EXISTS "product_source_sell_start_at_55064655" ON "commerce"."product_source" ("sell_start_at");
CREATE INDEX IF NOT EXISTS "product_source_snapshot_snapshot_date_4be98133" ON "snapshot"."product_source_snapshot" ("snapshot_date");
CREATE INDEX IF NOT EXISTS "product_term_relation_type_7be4d3e1" ON "commerce"."product_term" ("relation_type");
CREATE INDEX IF NOT EXISTS "product_term_relation_type_7be4d3e1_like" ON "commerce"."product_term" ("relation_type" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "resale_snapshot_snapshot_date_2c1726d7" ON "snapshot"."resale_snapshot" ("snapshot_date");
CREATE INDEX IF NOT EXISTS "product_source_relation_from_product_source_id_21e068ed" ON "commerce"."product_source_relation" ("from_product_source_id");
CREATE INDEX IF NOT EXISTS "product_source_relation_to_product_source_id_8d1c4ba2" ON "commerce"."product_source_relation" ("to_product_source_id");
CREATE INDEX IF NOT EXISTS "product_term_relation_object_term_id_8b96ceca" ON "commerce"."product_term_relation" ("object_term_id");
CREATE INDEX IF NOT EXISTS "product_term_relation_product_source_id_92a17f85" ON "commerce"."product_term_relation" ("product_source_id");
CREATE INDEX IF NOT EXISTS "product_review_product_source_id_f0480474" ON "commerce"."product_review" ("product_source_id");
CREATE INDEX IF NOT EXISTS "product_term_relation_subject_term_id_b6147614" ON "commerce"."product_term_relation" ("subject_term_id");""",
])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_notification_plan_review"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(DATABASE_SQL, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ProductSourceRelation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "relation_type",
                            models.CharField(
                                choices=[
                                    ("RESALE_OF", "중고 매물의 원상품"),
                                    ("RELATED_USED", "관련 중고 매물"),
                                ],
                                max_length=50,
                            ),
                        ),
                        (
                            "evidence_source",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "db_table": '"commerce"."product_source_relation"',
                    },
                ),
                migrations.CreateModel(
                    name="ProductTermRelation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "relation_type",
                            models.CharField(
                                choices=[
                                    ("HAS_ATTRIBUTE", "속성 보유"),
                                    ("HAS_MATERIAL", "소재 보유"),
                                    ("HAS_COLOR", "색상 보유"),
                                    ("HAS_STYLE", "스타일 연관"),
                                    ("HAS_TPO", "TPO 연관"),
                                    ("PART_OF_SET", "세트 구성"),
                                    ("RELATED", "기타 연관"),
                                ],
                                db_index=True,
                                max_length=30,
                                verbose_name="관계 유형",
                            ),
                        ),
                        (
                            "evidence_text",
                            models.CharField(
                                blank=True,
                                default="",
                                max_length=500,
                                verbose_name="근거 텍스트",
                            ),
                        ),
                        (
                            "confidence",
                            models.FloatField(blank=True, null=True, verbose_name="신뢰도"),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                        ),
                    ],
                    options={
                        "db_table": '"commerce"."product_term_relation"',
                    },
                ),
                migrations.CreateModel(
                    name="Target",
                    fields=[
                        (
                            "term",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                primary_key=True,
                                related_name="target",
                                serialize=False,
                                to="core.dictionaryterm",
                            ),
                        ),
                        (
                            "target_type",
                            models.CharField(
                                choices=[
                                    ("HEIGHT", "신장"),
                                    ("BODY_SHAPE", "체형"),
                                    ("SIZE", "사이즈"),
                                    ("AGE", "연령"),
                                    ("GENDER", "성별"),
                                    ("LIFE_STAGE", "라이프스테이지"),
                                    ("ETC", "기타"),
                                ],
                                default="ETC",
                                max_length=30,
                            ),
                        ),
                    ],
                    options={
                        "db_table": '"dictionary"."target"',
                    },
                ),
                migrations.AlterModelOptions(
                    name="product",
                    options={},
                ),
                migrations.AlterModelOptions(
                    name="productreview",
                    options={},
                ),
                migrations.AlterModelOptions(
                    name="productsourcesnapshot",
                    options={
                        "ordering": ["-snapshot_date", "-observed_at"],
                        "verbose_name": "상품 스냅샷",
                        "verbose_name_plural": "상품 스냅샷",
                    },
                ),
                migrations.AlterModelOptions(
                    name="productterm",
                    options={
                        "verbose_name": "상품 특성 관계",
                        "verbose_name_plural": "상품 특성 관계",
                    },
                ),
                migrations.AlterModelOptions(
                    name="resalesnapshot",
                    options={
                        "ordering": ["-snapshot_date", "-observed_at"],
                        "verbose_name": "리셀 스냅샷",
                        "verbose_name_plural": "리셀 스냅샷",
                    },
                ),
                migrations.RemoveConstraint(
                    model_name="dictionaryterm",
                    name="ck_dict_term_type",
                ),
                migrations.RemoveConstraint(
                    model_name="productsourcesnapshot",
                    name="uq_prod_snapshot_scope",
                ),
                migrations.RemoveConstraint(
                    model_name="productterm",
                    name="uq_prodsrc_term",
                ),
                migrations.RemoveConstraint(
                    model_name="resalesnapshot",
                    name="uq_resale_snap",
                ),
                migrations.RemoveConstraint(
                    model_name="texttermmention",
                    name="ck_mention_evidence_range",
                ),
                migrations.RemoveIndex(
                    model_name="productsourcesnapshot",
                    name="idx_prod_snap_time",
                ),
                migrations.RemoveIndex(
                    model_name="productsourcesnapshot",
                    name="idx_prod_snap_prod_time",
                ),
                migrations.RemoveIndex(
                    model_name="resalesnapshot",
                    name="idx_resale_index",
                ),
                migrations.RemoveIndex(
                    model_name="resalesnapshot",
                    name="idx_resale_prod",
                ),
                migrations.AddField(
                    model_name="brand",
                    name="price_tier",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "저가"),
                            ("MID", "중가"),
                            ("HIGH", "고가"),
                            ("LUXURY", "럭셔리"),
                        ],
                        db_index=True,
                        help_text="브랜드의 전반적인 가격 포지션",
                        max_length=20,
                        null=True,
                        verbose_name="가격 포지션",
                    ),
                ),
                migrations.AddField(
                    model_name="brand",
                    name="product_categories",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="브랜드가 주력으로 전개하는 FEEDIT 상품 카테고리",
                        limit_choices_to={"category_type": "PRODUCT"},
                        related_name="brands_by_product_focus",
                        to="core.category",
                        verbose_name="주요 상품군",
                    ),
                ),
                migrations.AddField(
                    model_name="brand",
                    name="terms",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="브랜드를 설명하는 FEEDIT Dictionary Term",
                        related_name="brands",
                        to="core.dictionaryterm",
                        verbose_name="연관 키워드",
                    ),
                ),
                migrations.AddField(
                    model_name="product",
                    name="group_key",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        null=True,
                        verbose_name="상품 그룹 키",
                    ),
                ),
                migrations.AddField(
                    model_name="product",
                    name="styles",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="core.style",
                        verbose_name="스타일",
                    ),
                ),
                migrations.AddField(
                    model_name="productsource",
                    name="season",
                    field=models.CharField(
                        blank=True, db_index=True, max_length=50, null=True, verbose_name="시즌"
                    ),
                ),
                migrations.AddField(
                    model_name="productsource",
                    name="season_year",
                    field=models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="시즌 연도"
                    ),
                ),
                migrations.AddField(
                    model_name="productsource",
                    name="sell_end_at",
                    field=models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="판매 종료일시"
                    ),
                ),
                migrations.AddField(
                    model_name="productsource",
                    name="sell_start_at",
                    field=models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="판매 시작일시"
                    ),
                ),
                migrations.AddField(
                    model_name="productsource",
                    name="source_genders",
                    field=models.JSONField(
                        blank=True, default=list, verbose_name="플랫폼 성별 정보"
                    ),
                ),
                migrations.AddField(
                    model_name="productsourcesnapshot",
                    name="snapshot_date",
                    field=models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="한국 시간 기준 수집 날짜",
                        null=True,
                        verbose_name="스냅샷 기준일",
                    ),
                ),
                migrations.AddField(
                    model_name="productterm",
                    name="relation_type",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("HAS_ITEM", "아이템"),
                            ("HAS_MATERIAL", "소재"),
                            ("HAS_COLOR", "색상"),
                            ("HAS_FIT", "핏"),
                            ("HAS_SILHOUETTE", "실루엣"),
                            ("HAS_NECKLINE", "넥라인"),
                            ("HAS_SLEEVE", "소매"),
                            ("HAS_LENGTH", "기장"),
                            ("HAS_SHAPE", "형태"),
                            ("HAS_DETAIL", "디테일"),
                            ("HAS_STYLE", "스타일"),
                            ("HAS_TPO", "TPO"),
                        ],
                        db_index=True,
                        max_length=32,
                        null=True,
                        verbose_name="관계 유형",
                    ),
                ),
                migrations.AddField(
                    model_name="resalesnapshot",
                    name="snapshot_date",
                    field=models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="한국 시간 기준 수집 날짜",
                        null=True,
                        verbose_name="스냅샷 기준일",
                    ),
                ),
                migrations.AlterField(
                    model_name="dictionaryterm",
                    name="term_type",
                    field=models.CharField(
                        choices=[
                            ("BRAND", "브랜드"),
                            ("STYLE", "스타일"),
                            ("ITEM", "아이템"),
                            ("DETAIL", "디테일"),
                            ("MATERIAL", "소재"),
                            ("COLOR", "색상"),
                            ("TPO", "TPO"),
                            ("PERSON", "인물"),
                            ("TARGET", "타깃"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="용어 유형",
                    ),
                ),
                migrations.AlterField(
                    model_name="productsource",
                    name="mapping_status",
                    field=models.CharField(
                        choices=[
                            ("UNMAPPED", "표준 상품 미매핑"),
                            ("MAPPED", "표준 상품 연결 완료"),
                        ],
                        db_index=True,
                        default="UNMAPPED",
                        max_length=20,
                        verbose_name="상품 매핑 상태",
                    ),
                ),
                migrations.AlterField(
                    model_name="productsourcesnapshot",
                    name="observed_at",
                    field=models.DateTimeField(
                        db_index=True,
                        help_text="해당 날짜에 마지막으로 수집된 데이터의 관측 시각",
                        verbose_name="최종 관측일시",
                    ),
                ),
                migrations.AlterField(
                    model_name="resalesnapshot",
                    name="highest_bid",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="최고 구매 호가",
                    ),
                ),
                migrations.AlterField(
                    model_name="resalesnapshot",
                    name="lowest_ask",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="최저 판매 호가",
                    ),
                ),
                migrations.AlterField(
                    model_name="resalesnapshot",
                    name="market_metrics",
                    field=models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="사이즈별 가격 요약, 표본 통계, 수집 범위 및 플랫폼별 추가 시장 지표",
                        verbose_name="추가 시장 지표",
                    ),
                ),
                migrations.AlterField(
                    model_name="resalesnapshot",
                    name="observed_at",
                    field=models.DateTimeField(
                        db_index=True,
                        help_text="해당 날짜에 마지막으로 수집된 데이터의 관측 시각",
                        verbose_name="최종 관측일시",
                    ),
                ),
                migrations.AlterField(
                    model_name="resalesnapshot",
                    name="resale_index",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="FEEDIT 분석 파이프라인에서 산출하는 지표",
                        max_digits=10,
                        null=True,
                        verbose_name="리셀 지수",
                    ),
                ),
                migrations.AlterField(
                    model_name="resalesnapshot",
                    name="resale_price_ratio",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="최근 거래가 / 검증된 발매가",
                        max_digits=10,
                        null=True,
                        verbose_name="리셀 가격 비율",
                    ),
                ),
                migrations.AlterField(
                    model_name="termcandidate",
                    name="suggested_type",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("BRAND", "브랜드"),
                            ("STYLE", "스타일"),
                            ("ITEM", "아이템"),
                            ("DETAIL", "디테일"),
                            ("MATERIAL", "소재"),
                            ("COLOR", "색상"),
                            ("TPO", "TPO"),
                            ("PERSON", "인물"),
                            ("TARGET", "타깃"),
                        ],
                        db_index=True,
                        max_length=30,
                        null=True,
                        verbose_name="추천 용어 유형",
                    ),
                ),
                migrations.AddIndex(
                    model_name="product",
                    index=models.Index(fields=["brand", "group_key"], name="idx_product_group"),
                ),
                migrations.AddIndex(
                    model_name="productsourcesnapshot",
                    index=models.Index(
                        fields=["-snapshot_date", "-observed_at"], name="idx_prod_snap_date"
                    ),
                ),
                migrations.AddIndex(
                    model_name="productsourcesnapshot",
                    index=models.Index(
                        fields=["product_source", "-snapshot_date"],
                        name="idx_prod_snap_prod_date",
                    ),
                ),
                migrations.AddIndex(
                    model_name="productterm",
                    index=models.Index(
                        fields=["relation_type", "term"], name="idx_prod_term_relation"
                    ),
                ),
                migrations.AddIndex(
                    model_name="resalesnapshot",
                    index=models.Index(
                        fields=["-snapshot_date", "-resale_index"], name="idx_resale_date_index"
                    ),
                ),
                migrations.AddIndex(
                    model_name="resalesnapshot",
                    index=models.Index(
                        fields=["product_source", "-snapshot_date"], name="idx_resale_prod_date"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="dictionaryterm",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "term_type__in",
                                [
                                    "BRAND",
                                    "STYLE",
                                    "ITEM",
                                    "DETAIL",
                                    "MATERIAL",
                                    "COLOR",
                                    "TPO",
                                    "PERSON",
                                    "TARGET",
                                ],
                            )
                        ),
                        name="ck_dict_term_type",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="productsourcesnapshot",
                    constraint=models.UniqueConstraint(
                        fields=("product_source", "snapshot_date", "ranking_scope"),
                        name="uq_prod_snapshot_daily_scope",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="productterm",
                    constraint=models.UniqueConstraint(
                        fields=("product_source", "term", "relation_type"),
                        name="uq_prodsrc_term_relation",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="resalesnapshot",
                    constraint=models.UniqueConstraint(
                        fields=("product_source", "snapshot_date"), name="uq_resale_daily"
                    ),
                ),
                migrations.AddField(
                    model_name="productsourcerelation",
                    name="from_product_source",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="core.productsource",
                    ),
                ),
                migrations.AddField(
                    model_name="productsourcerelation",
                    name="to_product_source",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="core.productsource",
                    ),
                ),
                migrations.AddField(
                    model_name="producttermrelation",
                    name="object_term",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_relation_objects",
                        to="core.dictionaryterm",
                        verbose_name="대상 용어",
                    ),
                ),
                migrations.AddField(
                    model_name="producttermrelation",
                    name="product_source",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_relations",
                        to="core.productsource",
                        verbose_name="소스 상품",
                    ),
                ),
                migrations.AddField(
                    model_name="producttermrelation",
                    name="subject_term",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_relation_subjects",
                        to="core.dictionaryterm",
                        verbose_name="주체 용어",
                    ),
                ),
                migrations.AddIndex(
                    model_name="productsourcerelation",
                    index=models.Index(
                        fields=["from_product_source", "relation_type"],
                        name="idx_prod_src_rel_from",
                    ),
                ),
                migrations.AddIndex(
                    model_name="productsourcerelation",
                    index=models.Index(
                        fields=["to_product_source", "relation_type"],
                        name="idx_prod_src_rel_to",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="productsourcerelation",
                    constraint=models.UniqueConstraint(
                        fields=("from_product_source", "to_product_source", "relation_type"),
                        name="uq_product_source_relation",
                    ),
                ),
                migrations.AddIndex(
                    model_name="producttermrelation",
                    index=models.Index(fields=["product_source"], name="idx_ptr_product"),
                ),
                migrations.AddIndex(
                    model_name="producttermrelation",
                    index=models.Index(
                        fields=["subject_term", "relation_type"], name="idx_ptr_subject_rel"
                    ),
                ),
                migrations.AddIndex(
                    model_name="producttermrelation",
                    index=models.Index(
                        fields=["object_term", "relation_type"], name="idx_ptr_object_rel"
                    ),
                ),
                migrations.AddIndex(
                    model_name="producttermrelation",
                    index=models.Index(
                        fields=["product_source", "subject_term"], name="idx_ptr_prod_subject"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="producttermrelation",
                    constraint=models.UniqueConstraint(
                        fields=(
                            "product_source",
                            "subject_term",
                            "relation_type",
                            "object_term",
                        ),
                        name="uq_prod_term_relation",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="producttermrelation",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("subject_term", models.F("object_term")), _negated=True
                        ),
                        name="ck_prod_term_rel_not_self",
                    ),
                ),
                # ── ProductReview: managed 로 바뀐 뒤의 필드 · 제약 (0054 와 같은 정의) ──
                migrations.AddField(
                    model_name="productreview",
                    name="product_source",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.productsource",
                    ),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name="productreview",
                    name="review_type",
                    field=models.CharField(blank=True, default="", max_length=30),
                ),
                migrations.AlterField(
                    model_name="productreview",
                    name="goods_option",
                    field=models.CharField(blank=True, default="", max_length=200),
                ),
                migrations.AlterField(
                    model_name="productreview",
                    name="like_count",
                    field=models.IntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name="productreview",
                    name="reviewer_sex",
                    field=models.CharField(blank=True, default="", max_length=20),
                ),
                migrations.AlterField(
                    model_name="productreview",
                    name="survey",
                    field=models.JSONField(blank=True, default=dict),
                ),
                migrations.AlterField(
                    model_name="productreview",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True),
                ),
                migrations.AddConstraint(
                    model_name="productreview",
                    constraint=models.UniqueConstraint(
                        fields=("product_source", "source_review_id"),
                        name="uq_product_review_source_review",
                    ),
                ),
            ],
        ),
    ]
